In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import logging
import sys

# Clear any existing handlers to prevent duplicates
root_logger = logging.getLogger()
if root_logger.handlers:
    for handler in root_logger.handlers:
        root_logger.removeHandler(handler)

# Configure logging FIRST before importing DataLoader
logging.basicConfig(level=logging.WARNING, force=True)

# Suppress specific loggers that are verbose
for logger_name in ['__main__', 'snowflake', 'azure', 'urllib3']:
    logging.getLogger(logger_name).setLevel(logging.WARNING)

# Add the project root to the path to import custom modules
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

# Import the DataLoader class
from scripts.data_preparation.load import DataLoader

print("✓ Libraries imported successfully")
print("✓ Logging configured (INFO messages suppressed)")

✓ Libraries imported successfully
✓ Logging configured (INFO messages suppressed)

In [2]:
# Getting email data from startdate to enddate
startdate = '2026-01-01'
enddate = '2026-05-11'

print(f"Tracking Email History will be Retrieved from {startdate} to {enddate}")

Tracking Email History will be Retrieved from 2026-01-01 to 2026-05-11

## 1. Load Tracking Email Data from Snowflake

Load the tracking email data from Snowflake using the DataLoader class.

In [3]:
# Execute the query to get historical load data
print("Querying Snowflake for Tracking Email data...")
print(f"Date Range: {startdate} to {enddate}")

loader = DataLoader()

df = loader.load_from_snowflake(
    sql_file_path='../sql/EmailExtractionToContextBuilder.sql',
    params={'startdate': startdate, 'enddate': enddate}
)

print(f"\n✓ Loaded {len(df):,} rows from Snowflake")
print(f"  Date range in data: {df['SENT_DATE'].min()} to {df['SENT_DATE'].max()}")
print(f"  Columns: {len(df.columns)}")
df.head()

Querying Snowflake for Tracking Email data...
Date Range: 2026-01-01 to 2026-05-11

/home/azureuser/trackingContextBuilder/trackingContextBuilder/scripts/data_preparation/load.py:160: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.snowflake_conn)

✓ Loaded 133,299 rows from Snowflake
  Date range in data: 2026-01-06 to 2026-05-11
  Columns: 19

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,EMAIL_TEXT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,TIME_SENT_UTC,SENT_DATE,SENT_HOUR,TIME_RECEIVED_UTC,MAILBOXES,CLASSIFICATION,CATEGORIES,MONTHSTARTDATE,WORKDAYS
0,AAQkAGQ5NDBiODYxLWNhZGQtNDFmYy1iYTU2LTEzZjIwMz...,ae1cf2ae-c27c-4e7c-8ec9-84a90b5e389c,RE: Booked Load #: 545963533,"<html><head>\r\n<meta http-equiv=""Content-Type...",HuntOps@chrobinson.com,chrobinson.com,1,"[\n ""team5@xtremeload.com"",\n ""dispatch@time...","[\n ""timeitlogisticsllc.com"",\n ""xtremeload....",[\n 0\n],2026-03-06 22:14:12.857814,2026-03-06,22,2026-03-06 22:14:12,"[\n {\n ""EmailId"": """",\n ""MailboxId"": ""...",tracking-request,[],2026-03-01,22
1,AAQkADY2ZTU5MjBjLWQyMjEtNDk4Ni1hYjk0LWJkNGFmY2...,4ecaa5ab-7148-457e-b313-2d02656a8e79,RE: CHR Load # 547538895,"<html><head>\r\n<meta http-equiv=""Content-Type...",USPS-Team@chrobinson.com,chrobinson.com,1,"[\n ""dtstrucking1@gmail.com"",\n ""Korkentrux@...","[\n ""att.net"",\n ""gmail.com""\n]",[\n 0\n],2026-04-03 06:37:29.415144,2026-04-03,6,2026-04-03 06:37:29,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",tracking-request,[],2026-04-01,22
2,AAQkADY3NDYwNzgzLTFjZmMtNGFmMS04M2JhLTU3M2M0Mj...,77eb0e73-a5e9-4bab-9517-2e5491c8b10a,"RE: LTL entered - Laredo, TX 78045","<html><head>\r\n<meta http-equiv=""Content-Type...",15-Sonoco@chrobinson.com,chrobinson.com,1,"[\n ""SonocoTMS@chrobinson.com"",\n ""Melissa.S...","[\n ""chrobinson.com"",\n ""sonoco.com"",\n ""So...","[\n 1,\n 0\n]",2026-04-15 19:24:45.306887,2026-04-15,19,2026-04-15 19:24:44,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",tracking-request,[],2026-04-01,22
3,AAQkAGZmN2I5Y2YyLWFmZjYtNGQzOS05MjgwLWViNTkwZT...,640a6598-aff5-4d93-9446-5b6e3fe7e1c5,RE: ON HAND 618-104841,"<html><head>\r\n<meta http-equiv=""Content-Type...",CountryArcherCHR@chrobinson.com,chrobinson.com,1,"[\n ""Nancy.Pellegrino@xpo.com"",\n ""Lucas.Gri...","[\n ""xpo.com"",\n ""chrobinson.com""\n]","[\n 1,\n 0\n]",2026-04-03 15:50:12.294091,2026-04-03,15,2026-04-03 15:50:11,"[\n {\n ""EmailId"": """",\n ""MailboxId"": ""...",tracking-request,[],2026-04-01,22
4,AAQkAGNhM2E0MWJhLTIyYTEtNGRiNy1hNmI0LThiOWI0ZG...,99e50c7a-bdbd-4397-a22b-f02f2dc7d7c8,RE: TSI RTV#32 & 33,"<html><head>\r\n<meta http-equiv=""Content-Type...",TSIreturns@chrobinson.com,chrobinson.com,1,"[\n ""RMA.Planner@DHL.com"",\n ""TSIreturns@chr...","[\n ""MFRM.com"",\n ""chrobinson.com"",\n ""DHL....","[\n 1,\n 0\n]",2026-04-01 13:24:53.122674,2026-04-01,13,2026-04-01 13:24:52,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",tracking-request,[],2026-04-01,22

In [4]:
# Creating UDF to remove \n from dictionary columns
def remove_characters(col: str | None) -> str:
    """Remove newline characters from string values.
    
    Args:
        col: Input string value

    Returns:
        String with newline characters removed
    """
    if col is None or pd.isna(col):
        return ''
    return str(col).replace('\n','')

In [5]:
object_cols = df.select_dtypes(include=['object']).columns.tolist()
print(f"Found {len(object_cols)} object columns to process")

Found 14 object columns to process

In [6]:
object_cols = df.select_dtypes(include=['object']).columns.tolist()
print(f"Found {len(object_cols)} object columns to process")

Found 14 object columns to process

In [7]:
# OPTIMIZED VERSION: Use vectorized string operations instead of apply()
# This is 10-50x faster and uses less memory

import gc

print("🚀 Removing newline characters from object columns...")
print(f"Processing {len(object_cols)} columns")
print("="*80)

for i, col in enumerate(object_cols, 1):
    print(f"  [{i}/{len(object_cols)}] Processing: {col}")
    
    # Use vectorized string operations - much faster than apply()
    # fillna('') handles None/NaN values, str.replace does the work
    df[col] = df[col].fillna('').astype(str).str.replace('\n', '', regex=False)
    
    # Free up memory every few columns
    if i % 5 == 0:
        gc.collect()

print("="*80)
print("✅ All columns processed successfully!")
print(f"Memory freed: {gc.collect()} objects")

🚀 Removing newline characters from object columns...
Processing 14 columns
================================================================================
  [1/14] Processing: CONVERSATION_ID
  [2/14] Processing: MESSAGE_ID
  [3/14] Processing: SUBJECT

  [4/14] Processing: EMAIL_TEXT
  [5/14] Processing: SENDER
  [6/14] Processing: SENDER_DOMAIN
  [7/14] Processing: RECIPIENT
  [5/14] Processing: SENDER
  [6/14] Processing: SENDER_DOMAIN
  [7/14] Processing: RECIPIENT
  [8/14] Processing: RECIPIENT_DOMAIN
  [9/14] Processing: RECIPIENT_IS_CHR
  [10/14] Processing: SENT_DATE
  [8/14] Processing: RECIPIENT_DOMAIN
  [9/14] Processing: RECIPIENT_IS_CHR
  [10/14] Processing: SENT_DATE
  [11/14] Processing: MAILBOXES
  [12/14] Processing: CLASSIFICATION
  [11/14] Processing: MAILBOXES
  [12/14] Processing: CLASSIFICATION
  [13/14] Processing: CATEGORIES
  [14/14] Processing: MONTHSTARTDATE
================================================================================
✅ All columns processed successfully!
Memory freed: 76 objects
  [13/14] Processing: CATEGORIES
  [14/14] Processing: MONTHSTARTDATE
================================================================================
✅ All columns processed successfully!
Memory freed: 76 objects

### Clean HTML from Email Text

Remove HTML tags and extract human-readable content from email bodies.

In [8]:
from bs4 import BeautifulSoup
import re

def clean_email_html(html_text: str | None) -> str:
    """
    Extract clean, human-readable text from HTML email content.
    
    Removes:
    - All HTML tags
    - Script and style elements
    - Excessive whitespace and newlines
    - Email headers (From:, To:, Sent:, etc.)
    - Common email signatures and disclaimers
    
    Args:
        html_text: Raw HTML email content
        
    Returns:
        Clean, human-readable text content
    """
    if pd.isna(html_text) or html_text == '':
        return ''
    
    try:
        # Parse HTML with BeautifulSoup
        soup = BeautifulSoup(str(html_text), 'html.parser')
        
        # Remove script, style, and meta tags (non-content elements)
        for element in soup(['script', 'style', 'meta', 'link', 'head']):
            element.decompose()
        
        # Get text content
        text = soup.get_text(separator=' ', strip=True)
        
        # Clean up common email artifacts
        # Remove email headers (From:, To:, Sent:, Subject:, etc.)
        text = re.sub(r'^(From|To|Sent|Date|Subject|Cc|Bcc):\s*.*?$', '', text, flags=re.MULTILINE | re.IGNORECASE)
        
        # Remove common disclaimer patterns
        disclaimer_patterns = [
            r'This email.*?confidential.*?intended recipient.*?[\r\n]+',
            r'CONFIDENTIALITY NOTICE:.*?[\r\n]+',
            r'This message.*?confidential.*?[\r\n]+',
            r'If you are not the intended recipient.*?[\r\n]+',
            r'Please consider the environment before printing this email.*?[\r\n]+',
        ]
        for pattern in disclaimer_patterns:
            text = re.sub(pattern, '', text, flags=re.IGNORECASE | re.DOTALL)
        
        # Remove excessive whitespace
        text = re.sub(r'\s+', ' ', text)  # Multiple spaces to single space
        text = re.sub(r'\n\s*\n+', '\n\n', text)  # Multiple newlines to double newline
        
        # Remove leading/trailing whitespace
        text = text.strip()
        
        return text
    
    except Exception as e:
        # If parsing fails, return original text with minimal cleaning
        print(f"Warning: HTML parsing failed, returning minimally cleaned text. Error: {e}")
        # At minimum, remove HTML tags with regex
        text = re.sub(r'<[^>]+>', ' ', str(html_text))
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

print("✅ HTML cleaning function created: clean_email_html()")

✅ HTML cleaning function created: clean_email_html()

### Optimized HTML Cleaning (Faster Single-Process Version)

A faster version that uses lxml directly and vectorized operations.

In [9]:
import re
from bs4 import BeautifulSoup

# Pre-compile regex patterns for better performance
HEADER_PATTERN = re.compile(r'^(From|To|Sent|Date|Subject|Cc|Bcc):\s*.*?$', re.MULTILINE | re.IGNORECASE)
DISCLAIMER_PATTERNS = [
    re.compile(r'This email.*?confidential.*?intended recipient.*?[\r\n]+', re.IGNORECASE | re.DOTALL),
    re.compile(r'CONFIDENTIALITY NOTICE:.*?[\r\n]+', re.IGNORECASE | re.DOTALL),
    re.compile(r'This message.*?confidential.*?[\r\n]+', re.IGNORECASE | re.DOTALL),
    re.compile(r'If you are not the intended recipient.*?[\r\n]+', re.IGNORECASE | re.DOTALL),
    re.compile(r'Please consider the environment before printing this email.*?[\r\n]+', re.IGNORECASE | re.DOTALL),
]
WHITESPACE_PATTERN = re.compile(r'\s+')
NEWLINE_PATTERN = re.compile(r'\n\s*\n+')
HTML_TAG_PATTERN = re.compile(r'<[^>]+>')

def clean_email_html_optimized(html_text: str | None) -> str:
    """
    Optimized version of clean_email_html with pre-compiled regex patterns.
    
    Args:
        html_text: Raw HTML email content
        
    Returns:
        Clean, human-readable text content
    """
    if pd.isna(html_text) or html_text == '':
        return ''
    
    try:
        # Parse HTML with BeautifulSoup (lxml parser is fastest)
        soup = BeautifulSoup(str(html_text), 'lxml')
        
        # Remove non-content elements
        for element in soup(['script', 'style', 'meta', 'link', 'head']):
            element.decompose()
        
        # Get text content
        text = soup.get_text(separator=' ', strip=True)
        
        # Remove email headers
        text = HEADER_PATTERN.sub('', text)
        
        # Remove disclaimers
        for pattern in DISCLAIMER_PATTERNS:
            text = pattern.sub('', text)
        
        # Clean whitespace
        text = WHITESPACE_PATTERN.sub(' ', text)
        text = NEWLINE_PATTERN.sub('\n\n', text)
        
        return text.strip()
    
    except Exception:
        # Fallback: minimal cleaning with regex
        text = HTML_TAG_PATTERN.sub(' ', str(html_text))
        text = WHITESPACE_PATTERN.sub(' ', text)
        return text.strip()

print("✅ Optimized cleaning function created: clean_email_html_optimized()")
print("   - Uses pre-compiled regex patterns for ~2-3x speed improvement")
print("   - Faster lxml parser")

✅ Optimized cleaning function created: clean_email_html_optimized()
   - Uses pre-compiled regex patterns for ~2-3x speed improvement
   - Faster lxml parser

### Apply Optimized Cleaning (Choose ONE option below)

**Option 1**: Use optimized single-process version (recommended for <50k emails)
**Option 2**: Use parallel processing version (recommended for 50k+ emails)

### Parallel HTML Cleaning Function (Optional)

Only needed if you want to use parallel processing for very large datasets (50k+ emails).

In [10]:
from multiprocessing import Pool, cpu_count
import time

def clean_email_batch(batch_data):
    """
    Clean a batch of emails (for parallel processing).
    
    Args:
        batch_data: Tuple of (batch_index, email_texts_list)
        
    Returns:
        Tuple of (batch_index, cleaned_texts_list)
    """
    batch_idx, emails = batch_data
    cleaned = [clean_email_html_optimized(email) for email in emails]
    return batch_idx, cleaned


def parallel_clean_emails(df, column_name='EMAIL_TEXT', num_workers=None, chunk_size=1000):
    """
    Clean HTML from emails using parallel processing.
    
    Args:
        df: DataFrame with email data
        column_name: Name of column containing HTML email text
        num_workers: Number of parallel workers (default: CPU count - 1)
        chunk_size: Number of emails per batch
        
    Returns:
        List of cleaned email texts in same order as input
    """
    if column_name not in df.columns:
        print(f"⚠️ Column '{column_name}' not found in dataframe")
        return []
    
    # Set number of workers
    if num_workers is None:
        num_workers = max(1, cpu_count() - 1)  # Leave one core free
    
    total_emails = len(df)
    print(f"\n{'='*80}")
    print(f"🚀 PARALLEL HTML CLEANING")
    print(f"{'='*80}")
    print(f"Total emails: {total_emails:,}")
    print(f"Workers: {num_workers}")
    print(f"Chunk size: {chunk_size:,}")
    print(f"Total chunks: {(total_emails + chunk_size - 1) // chunk_size}")
    print(f"{'='*80}\n")
    
    # Split data into chunks
    email_series = df[column_name]
    chunks = []
    for i in range(0, total_emails, chunk_size):
        chunk = email_series.iloc[i:i+chunk_size].tolist()
        chunks.append((i // chunk_size, chunk))
    
    print(f"Starting parallel processing...")
    start_time = time.time()
    
    # Process chunks in parallel
    with Pool(processes=num_workers) as pool:
        results = pool.map(clean_email_batch, chunks)
    
    end_time = time.time()
    elapsed_time = end_time - start_time
    
    # Sort results by batch index and flatten
    results.sort(key=lambda x: x[0])
    cleaned_emails = []
    for _, batch_cleaned in results:
        cleaned_emails.extend(batch_cleaned)
    
    print(f"\n✅ Parallel processing complete!")
    print(f"{'='*80}")
    print(f"⏱️  Total time: {elapsed_time:.1f} seconds ({elapsed_time/60:.1f} minutes)")
    print(f"   Average: {elapsed_time/total_emails*1000:.2f} ms per email")
    print(f"   Throughput: {total_emails/elapsed_time:.0f} emails/second")
    print(f"{'='*80}\n")
    
    return cleaned_emails

print("✅ Parallel cleaning function created: parallel_clean_emails()")
print("   Note: Uses clean_email_html_optimized() internally")

✅ Parallel cleaning function created: parallel_clean_emails()
   Note: Uses clean_email_html_optimized() internally

In [11]:
# # OPTION 1: Optimized Single-Process Version (2-3x faster than original)
# # Best for: 34k emails or less, simpler to use

# import time

# if 'EMAIL_TEXT' in df.columns:
#     print(f"🚀 Applying optimized HTML cleaning to {len(df):,} emails...")
#     print("="*80)
    
#     start_time = time.time()
#     df['EMAIL_TEXT_CLEAN'] = df['EMAIL_TEXT'].apply(clean_email_html_optimized)
#     end_time = time.time()
    
#     elapsed_time = end_time - start_time
    
#     print(f"\n✅ Optimized HTML cleaning complete!")
#     print(f"⏱️  Total time: {elapsed_time:.1f} seconds ({elapsed_time/60:.1f} minutes)")
#     print(f"   Average: {elapsed_time/len(df)*1000:.2f} ms per email")
#     print(f"   Throughput: {len(df)/elapsed_time:.0f} emails/second")
    
#     # Show before/after example
#     print(f"\n{'='*80}")
#     print(f"Example comparison (first email with content):")
#     print("="*80)
    
#     for idx in range(min(5, len(df))):
#         if pd.notna(df['EMAIL_TEXT'].iloc[idx]) and len(str(df['EMAIL_TEXT'].iloc[idx])) > 100:
#             print(f"\nORIGINAL (first 500 chars):")
#             print("-"*80)
#             print(str(df['EMAIL_TEXT'].iloc[idx])[:500])
#             print("\n" + "="*80)
#             print(f"\nCLEANED:")
#             print("-"*80)
#             print(str(df['EMAIL_TEXT_CLEAN'].iloc[idx])[:500])
#             print("\n" + "="*80)
#             break
    
#     # Statistics
#     avg_original_length = df['EMAIL_TEXT'].apply(lambda x: len(str(x)) if pd.notna(x) else 0).mean()
#     avg_clean_length = df['EMAIL_TEXT_CLEAN'].apply(lambda x: len(str(x)) if pd.notna(x) else 0).mean()
#     reduction_pct = ((avg_original_length - avg_clean_length) / avg_original_length * 100) if avg_original_length > 0 else 0
    
#     print(f"\n📊 Cleaning Statistics:")
#     print(f"  Average original length: {avg_original_length:,.0f} characters")
#     print(f"  Average cleaned length: {avg_clean_length:,.0f} characters")
#     print(f"  Size reduction: {reduction_pct:.1f}%")
#     print("="*80)
# else:
#     print("⚠️  EMAIL_TEXT column not found in dataframe")

In [12]:
# # OPTION 2: Parallel Processing Version (4-8x faster than original)
# # Best for: 50k+ emails, will use all available CPU cores
# # NOTE: Skip this cell if you already ran Option 1 above!

# if 'EMAIL_TEXT' in df.columns:
#     # Use parallel processing with reduced workers to prevent memory crashes
#     # IMPORTANT: Reduce num_workers if you experience kernel crashes
#     cleaned_emails = parallel_clean_emails(
#         df=df,
#         column_name='EMAIL_TEXT',
#         num_workers=2,     # REDUCED: Use 2-4 workers instead of all cores to prevent crashes
#         chunk_size=500     # REDUCED: Smaller chunks to reduce memory per worker
#     )
    
#     # Add cleaned emails to dataframe
#     df['EMAIL_TEXT_CLEAN'] = cleaned_emails
    
#     # Show before/after example
#     print(f"\nExample comparison (first email with content):")
#     print("="*80)
    
#     for idx in range(min(5, len(df))):
#         if pd.notna(df['EMAIL_TEXT'].iloc[idx]) and len(str(df['EMAIL_TEXT'].iloc[idx])) > 100:
#             print(f"\nORIGINAL (first 500 chars):")
#             print("-"*80)
#             print(str(df['EMAIL_TEXT'].iloc[idx])[:500])
#             print("\n" + "="*80)
#             print(f"\nCLEANED:")
#             print("-"*80)
#             print(str(df['EMAIL_TEXT_CLEAN'].iloc[idx])[:500])
#             print("\n" + "="*80)
#             break
    
#     # Statistics
#     avg_original_length = df['EMAIL_TEXT'].apply(lambda x: len(str(x)) if pd.notna(x) else 0).mean()
#     avg_clean_length = df['EMAIL_TEXT_CLEAN'].apply(lambda x: len(str(x)) if pd.notna(x) else 0).mean()
#     reduction_pct = ((avg_original_length - avg_clean_length) / avg_original_length * 100) if avg_original_length > 0 else 0
    
#     print(f"\n📊 Cleaning Statistics:")
#     print(f"  Average original length: {avg_original_length:,.0f} characters")
#     print(f"  Average cleaned length: {avg_clean_length:,.0f} characters")
#     print(f"  Size reduction: {reduction_pct:.1f}%")
# else:
#     print("⚠️  EMAIL_TEXT column not found in dataframe")

In [13]:
# OPTION 3: Safer Batch Parallel Processing (Prevents Kernel Crashes)
# This processes the dataframe in large batches to avoid memory overload

if 'EMAIL_TEXT' in df.columns:
    import gc
    import time
    
    # Configuration
    batch_size = 20000  # Process 20k emails at a time
    num_workers = 2     # Limited workers to prevent memory crash
    chunk_size = 500    # Smaller chunks per worker
    
    total_emails = len(df)
    num_batches = (total_emails + batch_size - 1) // batch_size
    
    print(f"🚀 SAFE BATCH PARALLEL PROCESSING")
    print(f"="*80)
    print(f"Total emails: {total_emails:,}")
    print(f"Batch size: {batch_size:,}")
    print(f"Number of batches: {num_batches}")
    print(f"Workers per batch: {num_workers}")
    print(f"="*80 + "\n")
    
    all_cleaned = []
    overall_start = time.time()
    
    for batch_num in range(num_batches):
        start_idx = batch_num * batch_size
        end_idx = min((batch_num + 1) * batch_size, total_emails)
        
        print(f"📧 Batch {batch_num + 1}/{num_batches}: Processing rows {start_idx:,} to {end_idx:,}...")
        
        # Extract batch
        batch_df = df.iloc[start_idx:end_idx].copy()
        
        # Process batch in parallel
        batch_cleaned = parallel_clean_emails(
            df=batch_df,
            column_name='EMAIL_TEXT',
            num_workers=num_workers,
            chunk_size=chunk_size
        )
        
        # Collect results
        all_cleaned.extend(batch_cleaned)
        
        # Clean up memory
        del batch_df
        del batch_cleaned
        gc.collect()
        
        print(f"✓ Batch {batch_num + 1} complete. Progress: {len(all_cleaned):,}/{total_emails:,}\n")
    
    # Add cleaned emails to dataframe
    df['EMAIL_TEXT_CLEAN'] = all_cleaned
    
    overall_time = time.time() - overall_start
    
    print(f"\n{'='*80}")
    print(f"✅ ALL BATCHES COMPLETE!")
    print(f"Total time: {overall_time:.1f} seconds ({overall_time/60:.1f} minutes)")
    print(f"Average: {overall_time/total_emails*1000:.2f} ms per email")
    print(f"{'='*80}")
    
    # Show statistics
    avg_original_length = df['EMAIL_TEXT'].apply(lambda x: len(str(x)) if pd.notna(x) else 0).mean()
    avg_clean_length = df['EMAIL_TEXT_CLEAN'].apply(lambda x: len(str(x)) if pd.notna(x) else 0).mean()
    reduction_pct = ((avg_original_length - avg_clean_length) / avg_original_length * 100) if avg_original_length > 0 else 0
    
    print(f"\n📊 Cleaning Statistics:")
    print(f"  Average original length: {avg_original_length:,.0f} characters")
    print(f"  Average cleaned length: {avg_clean_length:,.0f} characters")
    print(f"  Size reduction: {reduction_pct:.1f}%")
else:
    print("⚠️  EMAIL_TEXT column not found in dataframe")

🚀 SAFE BATCH PARALLEL PROCESSING
================================================================================
Total emails: 133,299
Batch size: 20,000
Number of batches: 7
Workers per batch: 2
================================================================================

📧 Batch 1/7: Processing rows 0 to 20,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 8.7 seconds (0.1 minutes)
   Average: 0.43 ms per email
   Throughput: 2309 emails/second
================================================================================

✓ Batch 1 complete. Progress: 20,000/133,299

📧 Batch 2/7: Processing rows 20,000 to 40,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.9 seconds (0.2 minutes)
   Average: 0.49 ms per email
   Throughput: 2027 emails/second
================================================================================

✓ Batch 2 complete. Progress: 40,000/133,299

📧 Batch 3/7: Processing rows 40,000 to 60,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.9 seconds (0.2 minutes)
   Average: 0.49 ms per email
   Throughput: 2027 emails/second
================================================================================

✓ Batch 2 complete. Progress: 40,000/133,299

📧 Batch 3/7: Processing rows 40,000 to 60,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.6 seconds (0.2 minutes)
   Average: 0.48 ms per email
   Throughput: 2077 emails/second
================================================================================

✓ Batch 3 complete. Progress: 60,000/133,299

📧 Batch 4/7: Processing rows 60,000 to 80,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.6 seconds (0.2 minutes)
   Average: 0.48 ms per email
   Throughput: 2077 emails/second
================================================================================

✓ Batch 3 complete. Progress: 60,000/133,299

📧 Batch 4/7: Processing rows 60,000 to 80,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.7 seconds (0.2 minutes)
   Average: 0.48 ms per email
   Throughput: 2065 emails/second
================================================================================

✓ Batch 4 complete. Progress: 80,000/133,299

📧 Batch 5/7: Processing rows 80,000 to 100,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.7 seconds (0.2 minutes)
   Average: 0.48 ms per email
   Throughput: 2065 emails/second
================================================================================

✓ Batch 4 complete. Progress: 80,000/133,299

📧 Batch 5/7: Processing rows 80,000 to 100,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.7 seconds (0.2 minutes)
   Average: 0.48 ms per email
   Throughput: 2068 emails/second
================================================================================

✓ Batch 5 complete. Progress: 100,000/133,299

📧 Batch 6/7: Processing rows 100,000 to 120,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.7 seconds (0.2 minutes)
   Average: 0.48 ms per email
   Throughput: 2068 emails/second
================================================================================

✓ Batch 5 complete. Progress: 100,000/133,299

📧 Batch 6/7: Processing rows 100,000 to 120,000...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 20,000
Workers: 2
Chunk size: 500
Total chunks: 40
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.8 seconds (0.2 minutes)
   Average: 0.49 ms per email
   Throughput: 2039 emails/second
================================================================================

✓ Batch 6 complete. Progress: 120,000/133,299

📧 Batch 7/7: Processing rows 120,000 to 133,299...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 13,299
Workers: 2
Chunk size: 500
Total chunks: 27
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 9.8 seconds (0.2 minutes)
   Average: 0.49 ms per email
   Throughput: 2039 emails/second
================================================================================

✓ Batch 6 complete. Progress: 120,000/133,299

📧 Batch 7/7: Processing rows 120,000 to 133,299...

================================================================================
🚀 PARALLEL HTML CLEANING
================================================================================
Total emails: 13,299
Workers: 2
Chunk size: 500
Total chunks: 27
================================================================================

Starting parallel processing...

✅ Parallel processing complete!
================================================================================
⏱️  Total time: 7.1 seconds (0.1 minutes)
   Average: 0.53 ms per email
   Throughput: 1873 emails/second
================================================================================

✓ Batch 7 complete. Progress: 133,299/133,299


✅ Parallel processing complete!
================================================================================
⏱️  Total time: 7.1 seconds (0.1 minutes)
   Average: 0.53 ms per email
   Throughput: 1873 emails/second
================================================================================

✓ Batch 7 complete. Progress: 133,299/133,299


================================================================================
✅ ALL BATCHES COMPLETE!
Total time: 65.5 seconds (1.1 minutes)
Average: 0.49 ms per email
================================================================================

================================================================================
✅ ALL BATCHES COMPLETE!
Total time: 65.5 seconds (1.1 minutes)
Average: 0.49 ms per email
================================================================================

📊 Cleaning Statistics:
  Average original length: 66,726 characters
  Average cleaned length: 10,197 characters
  Size reduction: 84.7%

📊 Cleaning Statistics:
  Average original length: 66,726 characters
  Average cleaned length: 10,197 characters
  Size reduction: 84.7%

In [14]:
# df.groupby('CONVERSATION_ID').agg({'MESSAGE_ID':'nunique'}).sort_values(by='MESSAGE_ID', ascending=False).head(25)

In [15]:
# tester = df[df['CONVERSATION_ID']=='AAQkADlmYWY5NDg3LThjNmItNDAyNi1hYjBkLTZjNWU1NDAxOTY1YwAQACDHs14MmXhPhHUIc8IMo4s='].sort_values(by='TIME_SENT_UTC')
# tester.to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/tester_email_thread.csv', index=False)
# tester

## 2. Load Tracking Identifier Crosswalk Data from Snowflake

This will allow mapping of emails back to individual Ccodes

In [16]:
# Execute the query to get historical load data
print("Querying Snowflake for Tracking Identifier Crosswalk data...")
print(f"Date Range: {startdate} to {enddate}")

loader = DataLoader()

crosswalk_raw = loader.load_from_snowflake(
    sql_file_path='../sql/loadNumbertoReferenceNumMatching.sql',
    params={'startdate': startdate}
)

print(f"\n✓ Loaded {len(crosswalk_raw):,} rows from Snowflake")
print(f"  Original columns: {len(crosswalk_raw.columns)}")

# Restructure crosswalk to have one row per (loadnumber, partycode, carrier) combination
# Group by load/party/carrier and aggregate REFNUMs into arrays
print("\nRestructuring crosswalk: grouping by loadnumber, partycode, carrier...")
crosswalk_df = crosswalk_raw.groupby(
    ['LOADNUMBER', 'PARTYCODE', 'CARRIER_CODE', 'CARRIER_NAME'], 
    dropna=False
).agg({
    'REFNUM': lambda x: list(x.dropna().unique())  # Collect unique REFNUMs as array
}).reset_index()

# Rename the aggregated column for clarity
crosswalk_df.rename(columns={'REFNUM': 'REFNUMS'}, inplace=True)

print(f"✓ Crosswalk restructured!")
print(f"  Original rows: {len(crosswalk_raw):,}")
print(f"  Grouped rows: {len(crosswalk_df):,} (one per load/party/carrier)")
print(f"  Columns: {list(crosswalk_df.columns)}")

# Show example of REFNUMS array
print(f"\nExample REFNUMS array:")
if len(crosswalk_df) > 0:
    example_row = crosswalk_df.iloc[0]
    print(f"  Load: {example_row['LOADNUMBER']}")
    print(f"  REFNUMs: {example_row['REFNUMS'][:5]}..." if len(example_row['REFNUMS']) > 5 else f"  REFNUMs: {example_row['REFNUMS']}")

crosswalk_df.head()

Querying Snowflake for Tracking Identifier Crosswalk data...
Date Range: 2026-01-01 to 2026-05-11

/home/azureuser/trackingContextBuilder/trackingContextBuilder/scripts/data_preparation/load.py:160: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.snowflake_conn)

✓ Loaded 11,649,482 rows from Snowflake
  Original columns: 5

Restructuring crosswalk: grouping by loadnumber, partycode, carrier...
✓ Crosswalk restructured!
  Original rows: 11,649,482
  Grouped rows: 2,086,773 (one per load/party/carrier)
  Columns: ['LOADNUMBER', 'PARTYCODE', 'CARRIER_CODE', 'CARRIER_NAME', 'REFNUMS']

Example REFNUMS array:
  Load: 512914816
  REFNUMs: ['512914816', '1683011516', '3500053163 – Monica Howe']
✓ Crosswalk restructured!
  Original rows: 11,649,482
  Grouped rows: 2,086,773 (one per load/party/carrier)
  Columns: ['LOADNUMBER', 'PARTYCODE', 'CARRIER_CODE', 'CARRIER_NAME', 'REFNUMS']

Example REFNUMS array:
  Load: 512914816
  REFNUMs: ['512914816', '1683011516', '3500053163 – Monica Howe']

,LOADNUMBER,PARTYCODE,CARRIER_CODE,CARRIER_NAME,REFNUMS
0,512914816,C3556020,T5147519,P W D TRANSPORTATION INC,"[512914816, 1683011516, 3500053163 – Monica Howe]"
1,516445001,C8871524,T693387,"Transportes de Carga Fema, SA de CV","[1716919697, 190995424 / 9965264, 516445001]"
2,517227827,C8404407,T707156,"Transportes Lar-Mex, S.A. De C.V.","[4507875157, 517227827, 1724404840, 4507875157..."
3,523533456,C269152,T1570667,Rotex Transportation Inc,"[YHDYABV6Z6DT884, 1723343558, 523533456, RD-5561]"
4,527729067,C8765865,T4412684,HSD TRUCKING INC,"[527729067, 1722458896, Green Valley]"

## 3. Extract Load Identifiers from Email Subjects

Create functions to:
1. Extract potential load identifiers from email subject lines (patterns like "Load #: 123456", "REF #: 123456", etc.)
2. Match extracted identifiers against the crosswalk data to find associated party codes

In [17]:
import re
from typing import List

def extract_load_identifiers(subject: str) -> List[str]:
    """
    Extract potential load identifiers from an email subject line.
    
    Patterns detected:
    - 8-12 digit numbers (common load number format)
    - Letter-digit combinations (e.g., CHR123456, ABC-123456)
    - "Load #: 123456" or "Load#: 123456"
    - "REF #: 123456" or "REF#: 123456"
    - "Load 123456" or "Load# 123456"
    - "Reference: 123456" or "Ref: 123456"
    - "Order: 123456" or "ORD# 123456"
    - "Shipment: 123456" or "SHIP# 123456"
    - Standalone numbers that could be load numbers (6+ digits)
    - Alphanumeric identifiers like "CHR123456", "L-123456", etc.
    
    Args:
        subject: Email subject line
        
    Returns:
        List of unique potential load identifiers (as strings)
    """
    if pd.isna(subject) or not isinstance(subject, str):
        return []
    
    subject_upper = str(subject).upper()
    identifiers = set()
    
    # Pattern 1: 8-12 digit numbers (common load number format)
    pattern1 = re.findall(r'\b\d{8,12}\b', subject_upper)
    identifiers.update(pattern1)
    
    # Pattern 2: Letter-digit combinations (e.g., CHR123456, ABC-123456)
    pattern2 = re.findall(r'\b[A-Z]{2,4}-?\d{6,10}\b', subject_upper)
    identifiers.update(pattern2)
    
    # Pattern 3: Reference patterns (REF: 123456, REF# 123456, Reference: 123456)
    pattern3 = re.findall(r'(?:REF(?:ERENCE)?)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern3)
    
    # Pattern 4: Load patterns (LOAD: 123456, LID: 123456, Load# 123456)
    pattern4 = re.findall(r'(?:LOAD|LID)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern4)
    
    # Pattern 5: Order patterns (ORDER: 123456, ORD# 123456)
    pattern5 = re.findall(r'(?:ORDER|ORD)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern5)
    
    # Pattern 6: Shipment patterns (SHIPMENT: 123456, SHIP# 123456)
    pattern6 = re.findall(r'(?:SHIPMENT|SHIP)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern6)
    
    # Pattern 7: Common prefixes followed by numbers/alphanumeric
    # Matches: "CHR123456", "L-123456", "LOAD-123"
    pattern7 = re.findall(r'\b(?:CHR|L)[:\-\s]?([A-Z0-9]+)\b', subject_upper)
    identifiers.update(pattern7)
    
    # Pattern 8: Standalone numbers that could be load numbers (6-7 digits)
    # This catches shorter numbers that might be load IDs without keywords
    pattern8 = re.findall(r'\b(\d{6,7})\b', subject_upper)
    identifiers.update(pattern8)
    
    # Pattern 9: Hash/pound sign followed by number
    # Matches: "#123456", "# 123456"
    pattern9 = re.findall(r'#\s*(\d{6,12})\b', subject_upper)
    identifiers.update(pattern9)
    
    # Clean up and return unique identifiers
    # Remove any empty strings and ensure all are uppercase
    cleaned_identifiers = [id.strip().upper() for id in identifiers if id.strip()]
    
    return list(set(cleaned_identifiers))  # Return unique values only


print("✓ Load identifier extraction function created")
print("  - extract_load_identifiers(): Extract IDs from subject line")

✓ Load identifier extraction function created
  - extract_load_identifiers(): Extract IDs from subject line

In [18]:
# Batch processing function to enrich dataframe with crosswalk data
def enrich_emails_with_crosswalk(email_df, crosswalk_df, chunk_size=100000):
    """
    Process emails in chunks and add loadnumber, partycode, carrier_code, and carrier_name columns from crosswalk matches.
    
    Args:
        email_df: DataFrame with email data including SUBJECT column
        crosswalk_df: DataFrame with LOADNUMBER, PARTYCODE, CARRIER_CODE, CARRIER_NAME, REFNUMS (array) columns
        chunk_size: Number of rows to process per chunk
        
    Returns:
        DataFrame with added columns: extracted_identifiers, matched_refnums, loadnumbers, partycodes, carrier_code, carrier_name, match_count
    """
    import gc
    
    total_rows = len(email_df)
    num_chunks = (total_rows + chunk_size - 1) // chunk_size
    
    print(f"\n{'='*80}")
    print(f"Enriching Email DataFrame with Crosswalk Data (Batch Processing)")
    print(f"{'='*80}")
    print(f"Total emails: {total_rows:,}")
    print(f"Chunk size: {chunk_size:,}")
    print(f"Number of chunks: {num_chunks}")
    print(f"Crosswalk records: {len(crosswalk_df):,}")
    print(f"{'='*80}\n")
    
    # Build crosswalk lookup once for efficiency (optimized vectorized approach)
    # New structure: REFNUM -> load/party/carrier info
    print("Building crosswalk lookup dictionary (optimized)...")
    crosswalk_lookup = {}
    
    # Use vectorized operations instead of iterrows for better performance
    for idx in range(len(crosswalk_df)):
        row = crosswalk_df.iloc[idx]
        refnums_list = row['REFNUMS']
        
        if isinstance(refnums_list, list) and len(refnums_list) > 0:
            # Pre-create the lookup value once for all REFNUMs in this row
            lookup_value = {
                'loadnumber': str(row['LOADNUMBER']),
                'partycode': row['PARTYCODE'],
                'carrier_code': row['CARRIER_CODE'] if pd.notna(row.get('CARRIER_CODE')) else None,
                'carrier_name': row['CARRIER_NAME'] if pd.notna(row.get('CARRIER_NAME')) else None
            }
            
            # Map each REFNUM to the same lookup value
            for refnum in refnums_list:
                if pd.notna(refnum):
                    refnum_upper = str(refnum).upper()
                    if refnum_upper:
                        crosswalk_lookup[refnum_upper] = lookup_value
    
    print(f"✓ Crosswalk lookup built with {len(crosswalk_lookup):,} unique REFNUMs\n")
    
    # Initialize result lists
    all_extracted_ids = []
    all_matched_refnums = []
    all_loadnumbers = []
    all_partycodes = []
    all_carrier_codes = []
    all_carrier_names = []
    all_match_counts = []
    
    # Process in chunks
    for chunk_num in range(num_chunks):
        start_idx = chunk_num * chunk_size
        end_idx = min((chunk_num + 1) * chunk_size, total_rows)
        
        print(f"📧 Processing chunk {chunk_num + 1}/{num_chunks}: rows {start_idx:,} to {end_idx:,}...")
        
        # Get chunk
        chunk = email_df.iloc[start_idx:end_idx]
        
        # Process each email in chunk
        chunk_extracted = []
        chunk_matched = []
        chunk_loadnums = []
        chunk_partycodes = []
        chunk_carrier_codes = []
        chunk_carrier_names = []
        chunk_counts = []
        
        for _, row in chunk.iterrows():
            # Extract identifiers
            extracted_ids = extract_load_identifiers(row['SUBJECT'])
            
            # Match against crosswalk
            matched_refnums = []
            loadnumbers = set()
            partycodes = set()
            carrier_code = None  # Single value, not a set
            carrier_name = None  # Single value, not a set
            
            for identifier in extracted_ids:
                identifier_upper = identifier.upper()
                if identifier_upper in crosswalk_lookup:
                    matched_refnums.append(identifier_upper)
                    loadnumbers.add(crosswalk_lookup[identifier_upper]['loadnumber'])
                    partycodes.add(crosswalk_lookup[identifier_upper]['partycode'])
                    # Get the first carrier_code and carrier_name found (since there's only one per email)
                    if carrier_code is None:
                        carrier_code = crosswalk_lookup[identifier_upper]['carrier_code']
                    if carrier_name is None:
                        carrier_name = crosswalk_lookup[identifier_upper]['carrier_name']
            
            # Store results
            chunk_extracted.append(extracted_ids)
            chunk_matched.append(matched_refnums)
            chunk_loadnums.append(list(loadnumbers))
            chunk_partycodes.append(list(partycodes))
            chunk_carrier_codes.append(carrier_code)  # Store as single value
            chunk_carrier_names.append(carrier_name)  # Store as single value
            chunk_counts.append(len(matched_refnums))
        
        # Add chunk results to all results
        all_extracted_ids.extend(chunk_extracted)
        all_matched_refnums.extend(chunk_matched)
        all_loadnumbers.extend(chunk_loadnums)
        all_partycodes.extend(chunk_partycodes)
        all_carrier_codes.extend(chunk_carrier_codes)
        all_carrier_names.extend(chunk_carrier_names)
        all_match_counts.extend(chunk_counts)
        
        # Clean up
        del chunk
        gc.collect()
    
    # Add columns to original dataframe
    print(f"\n✓ All chunks processed. Adding columns to dataframe...")
    email_df['extracted_identifiers'] = all_extracted_ids
    email_df['matched_refnums'] = all_matched_refnums
    email_df['loadnumbers'] = all_loadnumbers
    email_df['partycodes'] = all_partycodes
    email_df['carrier_code'] = all_carrier_codes  # Single string value
    email_df['carrier_name'] = all_carrier_names  # Single string value
    email_df['match_count'] = all_match_counts
    
    # Print summary statistics
    print(f"\n{'='*80}")
    print(f"📊 Enrichment Summary")
    print(f"{'='*80}")
    
    emails_with_extracted = sum(1 for x in all_extracted_ids if len(x) > 0)
    emails_with_matches = sum(1 for x in all_match_counts if x > 0)
    total_loadnums = sum(len(x) for x in all_loadnumbers)
    total_partycodes = sum(len(x) for x in all_partycodes)
    emails_with_carrier_code = sum(1 for x in all_carrier_codes if pd.notna(x))
    
    print(f"Emails with extracted identifiers: {emails_with_extracted:,} ({emails_with_extracted/total_rows*100:.1f}%)")
    print(f"Emails with crosswalk matches: {emails_with_matches:,} ({emails_with_matches/total_rows*100:.1f}%)")
    print(f"Total load numbers found: {total_loadnums:,}")
    print(f"Total party codes found: {total_partycodes:,}")
    print(f"Emails with carrier code: {emails_with_carrier_code:,} ({emails_with_carrier_code/total_rows*100:.1f}%)")
    print(f"Average identifiers per email: {sum(len(x) for x in all_extracted_ids)/total_rows:.2f}")
    print(f"Average matches per email: {sum(all_match_counts)/total_rows:.2f}")
    print(f"{'='*80}\n")
    
    return email_df

print("✅ Batch enrichment function created: enrich_emails_with_crosswalk()")

✅ Batch enrichment function created: enrich_emails_with_crosswalk()

In [19]:
def extract_load_identifiers_from_body(body_text: str, limit: int = 20) -> List[str]:
    """
    Extract potential load identifiers from cleaned email body text.
    
    Uses same patterns as subject line extraction but applies to email body.
    Limits results to avoid extracting too many false positives from long emails.
    
    Args:
        body_text: Cleaned email body text
        limit: Maximum number of identifiers to extract (default: 20)
        
    Returns:
        List of unique potential load identifiers (as strings)
    """
    if pd.isna(body_text) or body_text == '':
        return []
    
    body_upper = str(body_text).upper()
    identifiers = set()
    
    # Pattern 1: 8-12 digit numbers (common load number format)
    pattern1 = re.findall(r'\b\d{8,12}\b', body_upper)
    identifiers.update(pattern1)
    
    # Pattern 2: Letter-digit combinations (e.g., CHR123456, ABC-123456)
    pattern2 = re.findall(r'\b[A-Z]{2,4}-?\d{6,10}\b', body_upper)
    identifiers.update(pattern2)
    
    # Pattern 3: Reference patterns (REF: 123456, REF# 123456, Reference: 123456)
    pattern3 = re.findall(r'(?:REF(?:ERENCE)?)[:\s#]*([A-Z0-9]{6,12})', body_upper)
    identifiers.update(pattern3)
    
    # Pattern 4: Load patterns (LOAD: 123456, LID: 123456, Load# 123456)
    pattern4 = re.findall(r'(?:LOAD|LID)[:\s#]*([A-Z0-9]{6,12})', body_upper)
    identifiers.update(pattern4)
    
    # Pattern 5: Order patterns (ORDER: 123456, ORD# 123456)
    pattern5 = re.findall(r'(?:ORDER|ORD)[:\s#]*([A-Z0-9]{6,12})', body_upper)
    identifiers.update(pattern5)
    
    # Pattern 6: Shipment patterns (SHIPMENT: 123456, SHIP# 123456)
    pattern6 = re.findall(r'(?:SHIPMENT|SHIP)[:\s#]*([A-Z0-9]{6,12})', body_upper)
    identifiers.update(pattern6)
    
    # Pattern 7: Common prefixes followed by numbers/alphanumeric
    pattern7 = re.findall(r'\b(?:CHR|L)[:\-\s]?([A-Z0-9]+)\b', body_upper)
    identifiers.update(pattern7)
    
    # Pattern 8: Hash/pound sign followed by number
    pattern8 = re.findall(r'#\s*(\d{6,12})\b', body_upper)
    identifiers.update(pattern8)
    
    # NOTE: Deliberately excluding 6-7 digit standalone numbers from body text
    # to reduce false positives (dates, phone numbers, etc.)
    
    # Clean up and return unique identifiers
    cleaned_identifiers = [id.strip().upper() for id in identifiers if id.strip()]
    
    # Filter out invalid identifiers:
    # 1. All-string identifiers (no digits) - e.g., "ABC", "LOAD"
    # 2. Single character identifiers - e.g., "A", "1"
    filtered_identifiers = []
    for identifier in cleaned_identifiers:
        # Skip single character identifiers
        if len(identifier) <= 1:
            continue
        # Skip all-letter identifiers (must contain at least one digit)
        if identifier.isalpha():
            continue
        # Keep valid identifiers
        filtered_identifiers.append(identifier)
    
    unique_identifiers = list(set(filtered_identifiers))
    
    # Limit results to avoid extracting too many from long emails
    return unique_identifiers[:limit]


print("✓ Body text identifier extraction function created")
print("  - extract_load_identifiers_from_body(): Extract IDs from email body")
print("  - Excludes: single characters, all-letter identifiers")
print("  - Note: Limits to 20 identifiers per email to reduce false positives")

✓ Body text identifier extraction function created
  - extract_load_identifiers_from_body(): Extract IDs from email body
  - Excludes: single characters, all-letter identifiers
  - Note: Limits to 20 identifiers per email to reduce false positives

### Extract Load Identifiers from Email Body Text

Similar to subject line extraction, extract potential load identifiers from the cleaned email body text.

In [20]:
def enrich_emails_with_crosswalk_enhanced(email_df, crosswalk_df, chunk_size=100000, 
                                          extract_from_body=True, body_column='EMAIL_TEXT_CLEAN'):
    """
    Process emails in chunks and extract identifiers from BOTH subject and body text.
    
    Args:
        email_df: DataFrame with email data including SUBJECT and body text columns
        crosswalk_df: DataFrame with LOADNUMBER, PARTYCODE, CARRIER_CODE, CARRIER_NAME, REFNUMS (array) columns
        chunk_size: Number of rows to process per chunk
        extract_from_body: Whether to also extract from email body (default: True)
        body_column: Column name containing cleaned email body text (default: 'EMAIL_TEXT_CLEAN')
        
    Returns:
        DataFrame with added columns including identifiers from subject AND body
    """
    import gc
    
    total_rows = len(email_df)
    num_chunks = (total_rows + chunk_size - 1) // chunk_size
    
    print(f"\n{'='*80}")
    print(f"Enhanced Email Enrichment (Subject + Body Text Extraction)")
    print(f"{'='*80}")
    print(f"Total emails: {total_rows:,}")
    print(f"Chunk size: {chunk_size:,}")
    print(f"Number of chunks: {num_chunks}")
    print(f"Crosswalk records: {len(crosswalk_df):,}")
    print(f"Extract from body: {extract_from_body}")
    if extract_from_body:
        print(f"Body text column: {body_column}")
    print(f"{'='*80}\n")
    
    # Build crosswalk lookup once for efficiency (optimized vectorized approach)
    # New structure: REFNUM -> load/party/carrier info
    print("Building crosswalk lookup dictionary (optimized)...")
    crosswalk_lookup = {}
    
    # Use vectorized operations instead of iterrows for better performance
    for idx in range(len(crosswalk_df)):
        row = crosswalk_df.iloc[idx]
        refnums_list = row['REFNUMS']
        
        if isinstance(refnums_list, list) and len(refnums_list) > 0:
            # Pre-create the lookup value once for all REFNUMs in this row
            lookup_value = {
                'loadnumber': str(row['LOADNUMBER']),
                'partycode': row['PARTYCODE'],
                'carrier_code': row['CARRIER_CODE'] if pd.notna(row.get('CARRIER_CODE')) else None,
                'carrier_name': row['CARRIER_NAME'] if pd.notna(row.get('CARRIER_NAME')) else None
            }
            
            # Map each REFNUM to the same lookup value
            for refnum in refnums_list:
                if pd.notna(refnum):
                    refnum_upper = str(refnum).upper()
                    if refnum_upper:
                        crosswalk_lookup[refnum_upper] = lookup_value
    
    print(f"✓ Crosswalk lookup built with {len(crosswalk_lookup):,} unique REFNUMs\n")
    
    # Initialize result lists
    all_extracted_ids_subject = []
    all_extracted_ids_body = []
    all_extracted_ids_combined = []
    all_matched_refnums = []
    all_loadnumbers = []
    all_partycodes = []
    all_carrier_codes = []
    all_carrier_names = []
    all_match_counts = []
    all_match_source = []  # Track where match came from: 'subject', 'body', or 'both'
    
    # Process in chunks
    for chunk_num in range(num_chunks):
        start_idx = chunk_num * chunk_size
        end_idx = min((chunk_num + 1) * chunk_size, total_rows)
        
        print(f"📧 Processing chunk {chunk_num + 1}/{num_chunks}: rows {start_idx:,} to {end_idx:,}...")
        
        # Get chunk
        chunk = email_df.iloc[start_idx:end_idx]
        
        # Process each email in chunk
        chunk_extracted_subject = []
        chunk_extracted_body = []
        chunk_extracted_combined = []
        chunk_matched = []
        chunk_loadnums = []
        chunk_partycodes = []
        chunk_carrier_codes = []
        chunk_carrier_names = []
        chunk_counts = []
        chunk_sources = []
        
        for _, row in chunk.iterrows():
            # Extract identifiers from subject
            extracted_ids_subject = extract_load_identifiers(row['SUBJECT'])
            
            # Extract identifiers from body (if enabled)
            extracted_ids_body = []
            if extract_from_body and body_column in email_df.columns:
                extracted_ids_body = extract_load_identifiers_from_body(row[body_column])
            
            # Combine unique identifiers from both sources
            all_ids = list(set(extracted_ids_subject + extracted_ids_body))
            
            # Match against crosswalk
            matched_refnums = []
            matched_from_subject = []
            matched_from_body = []
            loadnumbers = set()
            partycodes = set()
            carrier_code = None
            carrier_name = None
            
            for identifier in all_ids:
                identifier_upper = identifier.upper()
                if identifier_upper in crosswalk_lookup:
                    matched_refnums.append(identifier_upper)
                    loadnumbers.add(crosswalk_lookup[identifier_upper]['loadnumber'])
                    partycodes.add(crosswalk_lookup[identifier_upper]['partycode'])
                    
                    # Track source of match
                    if identifier_upper in [x.upper() for x in extracted_ids_subject]:
                        matched_from_subject.append(identifier_upper)
                    if identifier_upper in [x.upper() for x in extracted_ids_body]:
                        matched_from_body.append(identifier_upper)
                    
                    # Get the first carrier_code and carrier_name found
                    if carrier_code is None:
                        carrier_code = crosswalk_lookup[identifier_upper]['carrier_code']
                    if carrier_name is None:
                        carrier_name = crosswalk_lookup[identifier_upper]['carrier_name']
            
            # Determine match source
            if len(matched_from_subject) > 0 and len(matched_from_body) > 0:
                match_source = 'both'
            elif len(matched_from_subject) > 0:
                match_source = 'subject'
            elif len(matched_from_body) > 0:
                match_source = 'body'
            else:
                match_source = None
            
            # Store results
            chunk_extracted_subject.append(extracted_ids_subject)
            chunk_extracted_body.append(extracted_ids_body)
            chunk_extracted_combined.append(all_ids)
            chunk_matched.append(matched_refnums)
            chunk_loadnums.append(list(loadnumbers))
            chunk_partycodes.append(list(partycodes))
            chunk_carrier_codes.append(carrier_code)
            chunk_carrier_names.append(carrier_name)
            chunk_counts.append(len(matched_refnums))
            chunk_sources.append(match_source)
        
        # Add chunk results to all results
        all_extracted_ids_subject.extend(chunk_extracted_subject)
        all_extracted_ids_body.extend(chunk_extracted_body)
        all_extracted_ids_combined.extend(chunk_extracted_combined)
        all_matched_refnums.extend(chunk_matched)
        all_loadnumbers.extend(chunk_loadnums)
        all_partycodes.extend(chunk_partycodes)
        all_carrier_codes.extend(chunk_carrier_codes)
        all_carrier_names.extend(chunk_carrier_names)
        all_match_counts.extend(chunk_counts)
        all_match_source.extend(chunk_sources)
        
        # Clean up
        del chunk
        gc.collect()
    
    # Add columns to original dataframe
    print(f"\n✓ All chunks processed. Adding columns to dataframe...")
    email_df['extracted_ids_subject'] = all_extracted_ids_subject
    email_df['extracted_ids_body'] = all_extracted_ids_body
    email_df['extracted_identifiers'] = all_extracted_ids_combined
    email_df['matched_refnums'] = all_matched_refnums
    email_df['loadnumbers'] = all_loadnumbers
    email_df['partycodes'] = all_partycodes
    email_df['carrier_code'] = all_carrier_codes
    email_df['carrier_name'] = all_carrier_names
    email_df['match_count'] = all_match_counts
    email_df['match_source'] = all_match_source
    
    # Print summary statistics
    print(f"\n{'='*80}")
    print(f"📊 Enhanced Enrichment Summary")
    print(f"{'='*80}")
    
    emails_with_extracted_subject = sum(1 for x in all_extracted_ids_subject if len(x) > 0)
    emails_with_extracted_body = sum(1 for x in all_extracted_ids_body if len(x) > 0)
    emails_with_extracted_any = sum(1 for x in all_extracted_ids_combined if len(x) > 0)
    emails_with_matches = sum(1 for x in all_match_counts if x > 0)
    
    # Count matches by source
    matches_from_subject = sum(1 for x in all_match_source if x == 'subject')
    matches_from_body = sum(1 for x in all_match_source if x == 'body')
    matches_from_both = sum(1 for x in all_match_source if x == 'both')
    
    total_loadnums = sum(len(x) for x in all_loadnumbers)
    total_partycodes = sum(len(x) for x in all_partycodes)
    emails_with_carrier_code = sum(1 for x in all_carrier_codes if pd.notna(x))
    
    print(f"\n📧 Identifier Extraction:")
    print(f"  From subject only: {emails_with_extracted_subject:,} emails")
    print(f"  From body only: {emails_with_extracted_body:,} emails")
    print(f"  From either source: {emails_with_extracted_any:,} emails ({emails_with_extracted_any/total_rows*100:.1f}%)")
    
    print(f"\n🎯 Crosswalk Matches:")
    print(f"  Total emails with matches: {emails_with_matches:,} ({emails_with_matches/total_rows*100:.1f}%)")
    print(f"  Matched from subject: {matches_from_subject:,}")
    print(f"  Matched from body: {matches_from_body:,}")
    print(f"  Matched from both: {matches_from_both:,}")
    
    print(f"\n📦 Results:")
    print(f"  Total load numbers found: {total_loadnums:,}")
    print(f"  Total party codes found: {total_partycodes:,}")
    print(f"  Emails with carrier code: {emails_with_carrier_code:,} ({emails_with_carrier_code/total_rows*100:.1f}%)")
    print(f"  Average identifiers per email: {sum(len(x) for x in all_extracted_ids_combined)/total_rows:.2f}")
    print(f"  Average matches per email: {sum(all_match_counts)/total_rows:.2f}")
    print(f"{'='*80}\n")
    
    return email_df

print("✅ Enhanced enrichment function created: enrich_emails_with_crosswalk_enhanced()")
print("   - Extracts from both SUBJECT and EMAIL_TEXT_CLEAN")
print("   - Tracks match source (subject/body/both)")

✅ Enhanced enrichment function created: enrich_emails_with_crosswalk_enhanced()
   - Extracts from both SUBJECT and EMAIL_TEXT_CLEAN
   - Tracks match source (subject/body/both)

### Enhanced Enrichment: Extract from Subject AND Body Text

This enhanced version extracts identifiers from both the subject line and email body text.

### Enrich Email DataFrame with Crosswalk Data (Batch Processing)

In [21]:
# # Enrich the email dataframe with crosswalk data using batch processing
# # This will add the following columns:
# # - extracted_identifiers: All IDs found in subject
# # - matched_refnums: IDs that matched in crosswalk
# # - loadnumbers: Load numbers from crosswalk
# # - partycodes: Party codes from crosswalk
# # - match_count: Number of matches found

# df_enriched = enrich_emails_with_crosswalk(
#     email_df=df,
#     crosswalk_df=crosswalk_df,
#     chunk_size=100000  # Adjust based on your memory constraints
# )

# print("✅ Dataframe enriched with crosswalk data!")
# print(f"\nNew columns added: {['extracted_identifiers', 'matched_refnums', 'loadnumbers', 'partycodes', 'match_count']}")
# print(f"\nDataframe shape: {df_enriched.shape}")
# print(f"\nSample of enriched data:")
# df_enriched[['SUBJECT', 'extracted_identifiers', 'matched_refnums', 'loadnumbers', 'partycodes', 'match_count']].head(10)

In [22]:
# ENHANCED ENRICHMENT: Extract from BOTH Subject and Body Text
# This will significantly improve match rates by finding load identifiers
# mentioned in the email body that aren't in the subject line

df_enriched = enrich_emails_with_crosswalk_enhanced(
    email_df=df,
    crosswalk_df=crosswalk_df,
    chunk_size=100000,
    extract_from_body=True,
    body_column='EMAIL_TEXT_CLEAN'
)

print("\n✅ Enhanced dataframe enrichment complete!")
print(f"\nNew columns added:")
print(f"  - extracted_ids_subject: IDs found in subject line")
print(f"  - extracted_ids_body: IDs found in email body")
print(f"  - extracted_identifiers: Combined unique IDs from both")
print(f"  - matched_refnums: IDs that matched in crosswalk")
print(f"  - loadnumbers: Load numbers from crosswalk")
print(f"  - partycodes: Party codes from crosswalk")
print(f"  - carrier_code: Carrier code")
print(f"  - carrier_name: Carrier name")
print(f"  - match_count: Number of matches found")
print(f"  - match_source: Where match came from ('subject', 'body', or 'both')")

print(f"\nDataframe shape: {df_enriched.shape}")
print(f"\nSample of enriched data:")
df_enriched[['CONVERSATION_ID','MESSAGE_ID','SUBJECT', 'extracted_ids_subject', 'extracted_ids_body', 'match_source', 'match_count']].head(10)

================================================================================
Enhanced Email Enrichment (Subject + Body Text Extraction)
================================================================================
Total emails: 133,299
Chunk size: 100,000
Number of chunks: 2
Crosswalk records: 2,086,773
Extract from body: True
Body text column: EMAIL_TEXT_CLEAN
================================================================================

Building crosswalk lookup dictionary (optimized)...

✓ Crosswalk lookup built with 8,155,974 unique REFNUMs

📧 Processing chunk 1/2: rows 0 to 100,000...
📧 Processing chunk 2/2: rows 100,000 to 133,299...
📧 Processing chunk 2/2: rows 100,000 to 133,299...

✓ All chunks processed. Adding columns to dataframe...

================================================================================
📊 Enhanced Enrichment Summary
================================================================================

✓ All chunks processed. Adding columns to dataframe...

================================================================================
📊 Enhanced Enrichment Summary
================================================================================

📧 Identifier Extraction:
  From subject only: 95,279 emails
  From body only: 123,155 emails
  From either source: 128,775 emails (96.6%)

🎯 Crosswalk Matches:
  Total emails with matches: 90,653 (68.0%)
  Matched from subject: 8,040
  Matched from body: 34,167
  Matched from both: 48,446

📦 Results:
  Total load numbers found: 229,388
  Total party codes found: 112,287
  Emails with carrier code: 90,653 (68.0%)
  Average identifiers per email: 4.92
  Average matches per email: 2.11
================================================================================


📧 Identifier Extraction:
  From subject only: 95,279 emails
  From body only: 123,155 emails
  From either source: 128,775 emails (96.6%)

🎯 Crosswalk Matches:
  Total emails with matches: 90,653 (68.0%)
  Matched from subject: 8,040
  Matched from body: 34,167
  Matched from both: 48,446

📦 Results:
  Total load numbers found: 229,388
  Total party codes found: 112,287
  Emails with carrier code: 90,653 (68.0%)
  Average identifiers per email: 4.92
  Average matches per email: 2.11
================================================================================


✅ Enhanced dataframe enrichment complete!

New columns added:
  - extracted_ids_subject: IDs found in subject line
  - extracted_ids_body: IDs found in email body
  - extracted_identifiers: Combined unique IDs from both
  - matched_refnums: IDs that matched in crosswalk
  - loadnumbers: Load numbers from crosswalk
  - partycodes: Party codes from crosswalk
  - carrier_code: Carrier code
  - carrier_name: Carrier name
  - match_count: Number of matches found
  - match_source: Where match came from ('subject', 'body', or 'both')

Dataframe shape: (133299, 30)

Sample of enriched data:

✅ Enhanced dataframe enrichment complete!

New columns added:
  - extracted_ids_subject: IDs found in subject line
  - extracted_ids_body: IDs found in email body
  - extracted_identifiers: Combined unique IDs from both
  - matched_refnums: IDs that matched in crosswalk
  - loadnumbers: Load numbers from crosswalk
  - partycodes: Party codes from crosswalk
  - carrier_code: Carrier code
  - carrier_name: Carrier name
  - match_count: Number of matches found
  - match_source: Where match came from ('subject', 'body', or 'both')

Dataframe shape: (133299, 30)

Sample of enriched data:

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,extracted_ids_subject,extracted_ids_body,match_source,match_count
0,AAQkAGQ5NDBiODYxLWNhZGQtNDFmYy1iYTU2LTEzZjIwMz...,ae1cf2ae-c27c-4e7c-8ec9-84a90b5e389c,RE: Booked Load #: 545963533,"[545963533, OAD]","[545963533, 7616949195, 877]",both,2
1,AAQkADY2ZTU5MjBjLWQyMjEtNDk4Ni1hYjk0LWJkNGFmY2...,4ecaa5ab-7148-457e-b313-2d02656a8e79,RE: CHR Load # 547538895,"[547538895, LOAD]",[547538895],both,2
2,AAQkADY3NDYwNzgzLTFjZmMtNGFmMS04M2JhLTU3M2M0Mj...,77eb0e73-a5e9-4bab-9517-2e5491c8b10a,"RE: LTL entered - Laredo, TX 78045","[TL, AREDO]",[101806279],subject,1
3,AAQkAGZmN2I5Y2YyLWFmZjYtNGQzOS05MjgwLWViNTkwZT...,640a6598-aff5-4d93-9446-5b6e3fe7e1c5,RE: ON HAND 618-104841,[104841],"[548996566, 548039011]",None,0
4,AAQkAGNhM2E0MWJhLTIyYTEtNGRiNy1hNmI0LThiOWI0ZG...,99e50c7a-bdbd-4397-a22b-f02f2dc7d7c8,RE: TSI RTV#32 & 33,[],[],None,0
5,AAQkADEwYzc1MTljLWZjZmEtNGNhOS04YjExLWEwOWUwYW...,9e3f444a-406c-47a0-a34d-f6d63f0ec030,RE: logitech,[OGITECH],"[546234668, 545983363, 546236685]",None,0
6,AAQkAGUxYzZlYjM0LTVkMDMtNGY1ZC1iNzQ5LTkwN2MxMD...,5bd365fa-1718-4026-a62a-724e0a5bb0cc,RE: Navisphere Carrier Load Confirmation - Loa...,"[CONFIRMATION, OAD, 546574206]",[546574206],both,1
7,AAQkAGQ0ODYwMTM5LTM5ZDAtNDUxNi1iNmQyLWZlNTdlZj...,f7258e1a-034c-426a-a2a6-369bd19a9ec2,RE: Amsoil Truck Request 4/7,[],"[128144, 549537631]",body,1
8,AAQkADM2YTVkNGNlLWQ2ZjQtNGQ1OC1hNzBiLTJmZjZjMD...,0d07cf34-0116-4454-90f5-fd8b8b999f68,RE: 545726555,[545726555],"[128222, 8117629736, 546056176, 545726555, 127...",both,1
9,AAQkAGQ0ZTQ3ZjE3LTRhN2ItNDI0YS05YmQ2LWZmYzlmYW...,d91e8207-85c1-420b-b70e-493e69b1ead0,RE: RBQT LOAD DELIVERY STATUS,"[OAD, DELIVERY]","[550986071, 100001828168, 100001834358, 100001...",both,11

### Match Success Rate Summary

Analyze how many emails successfully matched to the crosswalk data.

In [23]:
# Analyze match success rate for the enriched dataframe
print("="*80)
print("📊 EMAIL MATCH SUCCESS RATE SUMMARY")
print("="*80)

total_emails = len(df_enriched)
emails_with_matches = len(df_enriched[df_enriched['match_count'] > 0])
emails_without_matches = total_emails - emails_with_matches

match_rate = (emails_with_matches / total_emails * 100) if total_emails > 0 else 0

print(f"\nTotal emails analyzed: {total_emails:,}")
print(f"\n✅ Emails with successful matches: {emails_with_matches:,}")
print(f"   Match rate: {match_rate:.2f}%")
print(f"\n❌ Emails without matches: {emails_without_matches:,}")
print(f"   No-match rate: {100 - match_rate:.2f}%")

# Breakdown by match source
if 'match_source' in df_enriched.columns:
    print(f"\n{'Match Source Breakdown:':-^80}")
    
    matched_from_subject = len(df_enriched[df_enriched['match_source'] == 'subject'])
    matched_from_body = len(df_enriched[df_enriched['match_source'] == 'body'])
    matched_from_both = len(df_enriched[df_enriched['match_source'] == 'both'])
    
    print(f"  Subject only: {matched_from_subject:,} ({matched_from_subject/total_emails*100:.2f}%)")
    print(f"  Body only: {matched_from_body:,} ({matched_from_body/total_emails*100:.2f}%)")
    print(f"  Both sources: {matched_from_both:,} ({matched_from_both/total_emails*100:.2f}%)")
    
    # Calculate value of body text extraction
    matches_including_body = matched_from_body + matched_from_both
    print(f"\n  💡 Total matches including body text: {matches_including_body:,}")
    print(f"     Additional value from body extraction: {matched_from_body + matched_from_both - matched_from_subject:,} emails")

# Statistics on match counts
if emails_with_matches > 0:
    matched_emails = df_enriched[df_enriched['match_count'] > 0]
    avg_matches = matched_emails['match_count'].mean()
    max_matches = matched_emails['match_count'].max()
    
    print(f"\n{'Match Statistics (for matched emails only):':-^80}")
    print(f"  Average matches per email: {avg_matches:.2f}")
    print(f"  Maximum matches in single email: {max_matches}")
    
    # Distribution of match counts
    match_count_dist = matched_emails['match_count'].value_counts().sort_index()
    print(f"\n  Match count distribution:")
    for count, num_emails in match_count_dist.head(10).items():
        print(f"    {int(count)} match(es): {num_emails:,} emails")

print("="*80)

================================================================================
📊 EMAIL MATCH SUCCESS RATE SUMMARY
================================================================================

Total emails analyzed: 133,299

✅ Emails with successful matches: 90,653
   Match rate: 68.01%

❌ Emails without matches: 42,646
   No-match rate: 31.99%

----------------------------Match Source Breakdown:-----------------------------
  Subject only: 8,040 (6.03%)
  Body only: 34,167 (25.63%)
  Both sources: 48,446 (36.34%)

  💡 Total matches including body text: 82,613
     Additional value from body extraction: 74,573 emails

------------------Match Statistics (for matched emails only):-------------------
  Average matches per email: 3.10
  Maximum matches in single email: 22

  Match count distribution:
    1 match(es): 47,845 emails
    2 match(es): 18,856 emails
    3 match(es): 5,828 emails
    4 match(es): 3,530 emails
    5 match(es): 1,636 emails
    6 match(es): 1,802 emails
    7 match(es): 943 emails
    8 match(es): 1,607 emails
    9 match(es): 810 emails
    10 match(es): 1,175 emails
================================================================================
  Subject only: 8,040 (6.03%)
  Body only: 34,167 (25.63%)
  Both sources: 48,446 (36.34%)

  💡 Total matches including body text: 82,613
     Additional value from body extraction: 74,573 emails

------------------Match Statistics (for matched emails only):-------------------
  Average matches per email: 3.10
  Maximum matches in single email: 22

  Match count distribution:
    1 match(es): 47,845 emails
    2 match(es): 18,856 emails
    3 match(es): 5,828 emails
    4 match(es): 3,530 emails
    5 match(es): 1,636 emails
    6 match(es): 1,802 emails
    7 match(es): 943 emails
    8 match(es): 1,607 emails
    9 match(es): 810 emails
    10 match(es): 1,175 emails
================================================================================

In [24]:
len(df_enriched)

133299

In [25]:
df_enriched = df_enriched.drop_duplicates(subset = ['MESSAGE_ID'], keep='first')
len(df_enriched)

133299

In [26]:
print(df_enriched[df_enriched['MESSAGE_ID']=='4fae0408-293b-4100-8bfc-86ac8c3b227d']['EMAIL_TEXT_CLEAN'])

Series([], Name: EMAIL_TEXT_CLEAN, dtype: object)

In [27]:
from IPython.display import display, HTML

# Display a single cell's content in a scrollable box
def show_cell_scrollable(text, max_height='400px', width='100%'):
    """Display text in a scrollable container"""
    html = f'''
    <div style="max-height: {max_height}; 
                width: {width}; 
                overflow-y: auto; 
                overflow-x: auto;
                border: 1px solid #ccc; 
                padding: 15px; 
                background-color: #f9f9f9;
                font-family: monospace;
                white-space: pre-wrap;
                word-wrap: break-word;">
        {text}
    </div>
    '''
    display(HTML(html))

# Example: Show a specific email
email_text = df_enriched[df_enriched['MESSAGE_ID']=='4fae0408-293b-4100-8bfc-86ac8c3b227d']['EMAIL_TEXT_CLEAN'].values[0]
show_cell_scrollable(email_text, max_height='500px')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [ ]:
# df_enriched.drop(columns=['EMAIL_TEXT','EMAIL_TEXT_CLEAN']).to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/enriched_matched_df.csv', index=False)

In [ ]:
# crosswalk_df.head()

In [ ]:
# crosswalk_df[crosswalk_df['LOADNUMBER']==552379931]

In [ ]:
# df_enriched[df_enriched['CONVERSATION_ID']=='AAQkADg0NTdmMTQzLWFjYWItNDkwYy04OTE1LTcxMzljZjhmNGE5MQAQALwBCjos5EFopwpWoR3eAyw='][['CONVERSATION_ID','MESSAGE_ID','SUBJECT','EMAIL_TEXT_CLEAN']]

In [ ]:
# # Search for a specific REFNUM value
# target_refnum = 'U'  # Replace with your actual value

# # Filter rows where target_refnum is in the REFNUMS array
# matching_rows = crosswalk_df[crosswalk_df['REFNUMS'].apply(lambda x: target_refnum in x if isinstance(x, list) else False)]

# print(f"Found {len(matching_rows)} records containing REFNUM: {target_refnum}")
# matching_rows

### Apply Enhanced Enrichment (Subject + Body Extraction)

Use the enhanced function to extract load identifiers from both subject lines AND email body text.

### Analyze Enriched Results

In [ ]:
# # Example 1: Filter emails that have matches
# emails_with_matches = df_enriched[df_enriched['match_count'] > 0]
# print(f"📊 Emails with crosswalk matches: {len(emails_with_matches):,}")
# print(f"\nSample matched emails:")
# print(emails_with_matches[['SUBJECT', 'matched_refnums', 'loadnumbers', 'partycodes']].head())

# print("\n" + "="*80 + "\n")

# # Example 2: Filter emails for a specific partycode
# if len(emails_with_matches) > 0 and len(emails_with_matches.iloc[0]['partycodes']) > 0:
#     example_partycode = emails_with_matches.iloc[0]['partycodes'][0]
#     emails_for_party = df_enriched[df_enriched['partycodes'].apply(lambda x: example_partycode in x)]
#     print(f"📧 Emails for partycode {example_partycode}: {len(emails_for_party):,}")
    
# print("\n" + "="*80 + "\n")

# # Example 3: Filter emails for a specific load number
# if len(emails_with_matches) > 0 and len(emails_with_matches.iloc[0]['loadnumbers']) > 0:
#     example_loadnum = emails_with_matches.iloc[0]['loadnumbers'][0]
#     emails_for_load = df_enriched[df_enriched['loadnumbers'].apply(lambda x: example_loadnum in x)]
#     print(f"📦 Emails for load number {example_loadnum}: {len(emails_for_load):,}")
#     print(emails_for_load[['SUBJECT', 'SENT_DATE', 'TIME_SENT_UTC']].head())

# print("\n" + "="*80 + "\n")

# # Example 4: Emails that didn't match
# no_match = df_enriched[df_enriched['match_count'] == 0]
# print(f"⚠️  Emails without matches: {len(no_match):,}")
# if len(no_match) > 0:
#     print("\nSample subjects without matches:")
#     for i, subject in enumerate(no_match['SUBJECT'].head(5)):
#         print(f"  {i+1}. {subject}")

In [ ]:
df_enriched.columns

Index(['CONVERSATION_ID', 'MESSAGE_ID', 'SUBJECT', 'EMAIL_TEXT', 'SENDER',
       'SENDER_DOMAIN', 'SENDER_IS_CHR', 'RECIPIENT', 'RECIPIENT_DOMAIN',
       'RECIPIENT_IS_CHR', 'TIME_SENT_UTC', 'SENT_DATE', 'SENT_HOUR',
       'TIME_RECEIVED_UTC', 'MAILBOXES', 'CLASSIFICATION', 'CATEGORIES',
       'MONTHSTARTDATE', 'WORKDAYS', 'EMAIL_TEXT_CLEAN',
       'extracted_ids_subject', 'extracted_ids_body', 'extracted_identifiers',
       'matched_refnums', 'loadnumbers', 'partycodes', 'carrier_code',
       'carrier_name', 'match_count', 'match_source'],
      dtype='object')

In [ ]:
matches_crosswalk = df_enriched[
    (df_enriched['partycodes'].notnull()) & 
    (df_enriched['partycodes'].apply(lambda x: len(x) > 0))
][['CONVERSATION_ID','loadnumbers','partycodes','carrier_code','carrier_name']].drop_duplicates(subset='CONVERSATION_ID', keep='first')
matches_crosswalk.shape

(112680, 5)

In [ ]:
df_final = pd.merge(df_enriched, matches_crosswalk.add_suffix('_final'), how='left', left_on='CONVERSATION_ID', right_on='CONVERSATION_ID_final')
df_final.shape

(494317, 35)

In [ ]:
matches_crosswalk[matches_crosswalk['CONVERSATION_ID']=='AAQkADcxNjMxYTgyLTc3NTYtNDdiYS1hMjYwLTJjZTAwYjZmZmZmNwAQAE797gsa2kF6lI0GjghCgLI=']

,CONVERSATION_ID,loadnumbers,partycodes,carrier_code,carrier_name
64514,AAQkADcxNjMxYTgyLTc3NTYtNDdiYS1hMjYwLTJjZTAwYj...,[549883632],[C665729],T3088892,A & I Express Inc

In [ ]:
df_final.groupby('MESSAGE_ID').agg({'CONVERSATION_ID':'count'}).reset_index().sort_values(by='CONVERSATION_ID', ascending=False)

                                  MESSAGE_ID  CONVERSATION_ID
0       000025ed-795d-42e7-911c-d1770af4131e                1
329584  aac961cb-5db8-458c-959c-2bf0b7d0335a                1
329552  aac578c4-1fb1-4061-bd9c-36ac0232df71                1
329551  aac56375-a616-4f73-a364-faf9eefc89f6                1
329550  aac4fa98-3ae6-4c12-8922-fb8c3a38b02d                1
...                                      ...              ...
164769  5578b9ab-bf9d-4fe7-baef-287c6556a3c4                1
164768  5578ace3-62fe-4570-b24d-419d8f7abc84                1
164767  55788b5f-4ccf-479a-8a39-b828c4b3491f                1
164766  55786b1e-4f80-40cd-b815-8c568e10f381                1
494316  fffffbf4-09b1-4dbf-9e3d-f877706bebc3                1

[494317 rows x 2 columns]

In [ ]:
# df_final[df_final['MESSAGE_ID']=='000099ee-7189-4a94-aeec-06d603a56210'].drop(columns=['EMAIL_TEXT']) #.to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/tester.csv', index=False)

In [ ]:
df_final = df_final.drop_duplicates(subset=['MESSAGE_ID'], keep='first')
df_final.shape

(494317, 35)

### Final Match Summary

In [ ]:
# Summary statistics for final matches
total_emails = len(df_final)

# Original match rate (before join with matches_crosswalk)
emails_with_original_match = df_enriched[
    (df_enriched['partycodes'].notnull()) & 
    (df_enriched['partycodes'].apply(lambda x: len(x) > 0))
]
num_original_matches = len(emails_with_original_match)
original_match_percentage = (num_original_matches / total_emails * 100) if total_emails > 0 else 0

# Final match rate (after join with matches_crosswalk)
emails_with_final_match = df_final[
    (df_final['partycodes_final'].notnull()) & 
    (df_final['partycodes_final'].apply(lambda x: len(x) > 0 if isinstance(x, list) else False))
]
num_emails_with_match = len(emails_with_final_match)
match_percentage = (num_emails_with_match / total_emails * 100) if total_emails > 0 else 0

print("="*80)
print("📊 FINAL MATCH SUMMARY")
print("="*80)
print(f"\nTotal emails in dataset: {total_emails:,}")

print(f"\n{'ORIGINAL MATCHES (df_enriched):':-^80}")
print(f"Emails with party code matches: {num_original_matches:,}")
print(f"Original match rate: {original_match_percentage:.2f}%")

print(f"\n{'FINAL MATCHES (df_final after join):':-^80}")
print(f"Emails with party code matches: {num_emails_with_match:,}")
print(f"Final match rate: {match_percentage:.2f}%")

print(f"\n{'COMPARISON:':-^80}")
if num_emails_with_match == num_original_matches:
    print(f"✓ Match rates are the same - no change from join")
else:
    diff = num_emails_with_match - num_original_matches
    diff_pct = match_percentage - original_match_percentage
    print(f"Change: {diff:+,} emails ({diff_pct:+.2f} percentage points)")

print(f"\nEmails without matches: {total_emails - num_emails_with_match:,} ({100 - match_percentage:.2f}%)")

# Count unique party codes and load numbers in final matches
if num_emails_with_match > 0:
    all_final_partycodes = set()
    all_final_loadnums = set()
    
    for _, row in emails_with_final_match.iterrows():
        if isinstance(row['partycodes_final'], list):
            all_final_partycodes.update(row['partycodes_final'])
        if isinstance(row['loadnumbers_final'], list):
            all_final_loadnums.update(row['loadnumbers_final'])
    
    print(f"\nUnique party codes identified: {len(all_final_partycodes):,}")
    print(f"Unique load numbers identified: {len(all_final_loadnums):,}")

print("="*80)

================================================================================
📊 FINAL MATCH SUMMARY
================================================================================

Total emails in dataset: 494,317

------------------------ORIGINAL MATCHES (df_enriched):-------------------------
Emails with party code matches: 310,770
Original match rate: 62.87%

----------------------FINAL MATCHES (df_final after join):----------------------
Emails with party code matches: 323,014
Final match rate: 65.35%

----------------------------------COMPARISON:-----------------------------------
Change: +12,244 emails (+2.48 percentage points)

Emails without matches: 171,303 (34.65%)

Unique party codes identified: 7,095
Unique load numbers identified: 151,118
================================================================================

Unique party codes identified: 7,095
Unique load numbers identified: 151,118
================================================================================

In [ ]:
# Dropping initial email text column
df_final = df_final.drop(columns=['EMAIL_TEXT'])

In [ ]:
df_final.columns

Index(['CONVERSATION_ID', 'MESSAGE_ID', 'SUBJECT', 'SENDER', 'SENDER_DOMAIN',
       'SENDER_IS_CHR', 'RECIPIENT', 'RECIPIENT_DOMAIN', 'RECIPIENT_IS_CHR',
       'TIME_SENT_UTC', 'SENT_DATE', 'SENT_HOUR', 'TIME_RECEIVED_UTC',
       'MAILBOXES', 'CLASSIFICATION', 'CATEGORIES', 'MONTHSTARTDATE',
       'WORKDAYS', 'EMAIL_TEXT_CLEAN', 'extracted_ids_subject',
       'extracted_ids_body', 'extracted_identifiers', 'matched_refnums',
       'loadnumbers', 'partycodes', 'carrier_code', 'carrier_name',
       'match_count', 'match_source', 'CONVERSATION_ID_final',
       'loadnumbers_final', 'partycodes_final', 'carrier_code_final',
       'carrier_name_final'],
      dtype='object')

## 4. Filter Out Internal CHR Emails

Remove emails where CHR is sending only to other CHR recipients (internal emails).
Keep emails where:
- SENDER_IS_CHR = 1 AND at least one recipient is external (RECIPIENT_IS_CHR contains 0)
- OR SENDER_IS_CHR = 0 (external sender)

In [ ]:
def filter_external_emails(df):
    """
    Filter out internal CHR emails (CHR sender to only CHR recipients).
    
    Keeps emails where:
    - SENDER_IS_CHR = 1 AND RECIPIENT_IS_CHR contains at least one 0 (external recipient)
    - OR SENDER_IS_CHR = 1 AND RECIPIENT_IS_CHR = [0] (only external recipients)
    - OR SENDER_IS_CHR = 0 (external sender - keep all regardless of recipients)
    
    Removes emails where:
    - SENDER_IS_CHR = 1 AND RECIPIENT_IS_CHR = [1] (only internal CHR recipients, no external)
    
    Args:
        df: DataFrame with SENDER_IS_CHR and RECIPIENT_IS_CHR columns
        
    Returns:
        Filtered DataFrame with internal CHR emails removed
    """
    import re
    
    original_count = len(df)
    
    def is_chr_only_recipients(recipient_str):
        """
        Check if RECIPIENT_IS_CHR array contains ONLY the value 1 (no 0s).
        
        The field is a string like "[  1]" or "[  0,  1]" or "[  0]"
        Returns True if the array contains only 1 (should be filtered out)
        Returns False if it contains 0 or both 0 and 1 (should be kept)
        """
        if pd.isna(recipient_str):
            return False
        
        # Convert string representation to actual values
        # Extract all digits from the string (ignoring brackets, spaces, commas)
        str_val = str(recipient_str)
        numbers = re.findall(r'\d+', str_val)
        
        if not numbers:
            return False
        
        # Convert to integers
        values = [int(n) for n in numbers]
        
        # Check if array contains ONLY 1 (no 0s)
        # If it contains only 1s and no 0s, return True (should filter)
        has_zero = 0 in values
        has_one = 1 in values
        
        # Return True if it has 1 but NOT 0 (chr only recipients)
        return has_one and not has_zero
    
    # Mask: Keep all emails EXCEPT those where sender is CHR AND recipients are CHR-only
    # In other words, remove rows where SENDER_IS_CHR=1 AND RECIPIENT_IS_CHR=[1]
    mask = ~(
        (df['SENDER_IS_CHR'] == 1) &  # CHR sender
        df['RECIPIENT_IS_CHR'].apply(is_chr_only_recipients)  # Only CHR recipients
    )
    
    df_filtered = df[mask].copy()
    
    removed_count = original_count - len(df_filtered)
    
    print("="*80)
    print("📧 INTERNAL EMAIL FILTERING")
    print("="*80)
    print(f"Original email count: {original_count:,}")
    print(f"Emails removed (CHR → only CHR recipients): {removed_count:,}")
    print(f"Emails remaining: {len(df_filtered):,}")
    print(f"Retention rate: {len(df_filtered)/original_count*100:.2f}%")
    print("="*80)
    
    return df_filtered

print("✅ Filter function created: filter_external_emails()")

✅ Filter function created: filter_external_emails()

In [ ]:
# df_final[df_final['SENDER_IS_CHR']==1]

In [ ]:
# # Diagnostic: Check the actual values in RECIPIENT_IS_CHR column
# print("Sample RECIPIENT_IS_CHR values:")
# print("="*80)
# sample_chr_senders = df_final[df_final['SENDER_IS_CHR']==1].head(20)
# for idx, row in sample_chr_senders.iterrows():
#     print(f"SENDER_IS_CHR: {row['SENDER_IS_CHR']}")
#     print(f"RECIPIENT_IS_CHR: {row['RECIPIENT_IS_CHR']} (type: {type(row['RECIPIENT_IS_CHR'])})")
#     print(f"Is list: {isinstance(row['RECIPIENT_IS_CHR'], list)}")
#     if isinstance(row['RECIPIENT_IS_CHR'], list):
#         print(f"List contents: {row['RECIPIENT_IS_CHR']}")
#         print(f"Has 0? {0 in row['RECIPIENT_IS_CHR']}")
#         print(f"Has 1? {1 in row['RECIPIENT_IS_CHR']}")
#     print("-"*40)

In [ ]:
# Apply the filter to remove internal CHR emails
df_final_filtered = filter_external_emails(df_final)

print(f"\n✅ Filtered dataframe created: df_final_filtered")
print(f"Shape: {df_final_filtered.shape}")
df_final_filtered.head()

================================================================================
📧 INTERNAL EMAIL FILTERING
================================================================================
Original email count: 494,317
Emails removed (CHR → only CHR recipients): 28,145
Emails remaining: 466,172
Retention rate: 94.31%
================================================================================

✅ Filtered dataframe created: df_final_filtered
Shape: (466172, 34)

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,TIME_SENT_UTC,...,partycodes,carrier_code,carrier_name,match_count,match_source,CONVERSATION_ID_final,loadnumbers_final,partycodes_final,carrier_code_final,carrier_name_final
0,AAQkAGJhNzliZmYyLTdlMjItNDVhNC05ZjQxLTk3YTBjY2...,674c4c6c-0f8c-472d-94dd-f963764506ea,RE: 3 MORE LOADS TO SHIP,stan@rushintermodal.com,rushintermodal.com,0,"[ ""Connor.Ellefson@chrobinson.com"", ""mike@ru...","[ ""chrobinson.com"", ""rushlogisticsgroup.com""...","[ 1, 0]",2026-03-06 16:50:18.542755,...,[],None,None,0,None,NaN,NaN,NaN,NaN,NaN
1,AAQkADkyNGI2ZmM5LTQ0NTgtNDEwOS04ZjYyLWRkZTQwOD...,ae54b8d5-6146-469e-b52c-fd846ce23713,RE: 544762051,Ashley.Schultz2@chrobinson.com,chrobinson.com,1,"[ ""Ashley.Schultz2@chrobinson.com"", ""MetroDe...","[ ""kupeltransport.com"", ""chrobinson.com""]","[ 0, 1]",2026-03-02 17:17:02.023100,...,[C8019327],T2138726,Kupel Transport LLC,1,both,AAQkADkyNGI2ZmM5LTQ0NTgtNDEwOS04ZjYyLWRkZTQwOD...,[544762051],[C8019327],T2138726,Kupel Transport LLC
2,AAQkADJlY2Q3OTU3LTY0ZWQtNDAxNi1iYjdjLWRhMTY5Yz...,10c4e3fa-aa4d-40a0-93d0-97d73b05a2ae,RE: PO#23999450-SO#370822,IPCCHROperations@chrobinson.com,chrobinson.com,1,"[ ""IPCCHROperations@chrobinson.com"", ""dulope...","[ ""chrobinson.com"", ""onelineage.com""]","[ 0, 1]",2026-03-11 15:09:13.815541,...,[C8734892],T5160094,IIK TRANSPORT INC,1,body,AAQkADJlY2Q3OTU3LTY0ZWQtNDAxNi1iYjdjLWRhMTY5Yz...,[545560497],[C8734892],T5160094,IIK TRANSPORT INC
3,AAQkADc4NGJhNDQ0LTM5MDQtNDVkMC05ODM5LWMwOTFkOT...,b130e5ef-f602-417b-a339-bf7da3dcdf5c,"RE: [EXTERNAL] MSE0EAT13L -304,306,326,330,346...",MadisonOps@chrobinson.com,chrobinson.com,1,"[ ""sophia.williams@uberfreight.com"", ""jose.f...","[ ""Eaton.com"", ""chrobinson.com"", ""transplac...","[ 0, 1]",2026-03-03 16:40:20.088647,...,[C512828],T5386501,UNITED FORCE TRUCKING LLC,4,body,AAQkADc4NGJhNDQ0LTM5MDQtNDVkMC05ODM5LWMwOTFkOT...,"[545357543, 545458986, 545459436, 545459227]",[C512828],T5386501,UNITED FORCE TRUCKING LLC
4,AAQkADY3NjljZWQ2LWNmNWQtNGI0Yy05YTg2LTc4N2Y0ZG...,2f43fcbd-dec5-4ffa-a55a-86d29eec4853,Re: Navisphere Carrier Load Confirmation - Loa...,syedat@directrightcartage.com,directrightcartage.com,0,"[ ""SaifAldin.Al-Ani@chrobinson.com""]","[ ""chrobinson.com""]",[ 1],2026-04-02 21:26:43.961043,...,[],None,None,0,None,NaN,NaN,NaN,NaN,NaN

## Filter to First CHR External Response

This filtering step isolates the initial portion of each email conversation — specifically, all emails sent **up to and including the first time a CHR employee responds to an external recipient**. 

**Purpose:** When analyzing what triggers CHR to initiate tracking requests, we want to examine the conversation context that existed at the moment CHR first engaged externally. Emails sent after that initial CHR response represent follow-up activity and are excluded from this analysis.

**Logic:** 
- For each conversation, find the first email where `SENDER_DOMAIN='chrobinson.com'` AND `RECIPIENT_DOMAIN` contains external (non-CHR) domains
- Keep all emails in that conversation with timestamps ≤ first CHR external response
- Remove conversations entirely if CHR never responded externally

---

### ⚠️ Known Limitation: Cross-Conversation Scenario

**Scenario:**
1. Customer → CHR tracking inbox (Conversation #1)
2. CHR person → Carrier email (Conversation #2 - separate thread)

**Current Behavior:** The filter operates **within each conversation**. It would keep:
- All emails in Conversation #1 (including customer→CHR emails)
- All emails in Conversation #2 (CHR→carrier)

**Desired Behavior:** Only keep CHR→**carrier** communications, not CHR→customer or customer→CHR.

**Future Enhancement:** Once carrier email identification data is available, add additional filtering to:
- Identify which external emails belong to carriers vs. customers
- Filter to only conversations where CHR is communicating with carrier contacts
- Or filter individual emails where recipient/sender is identified as a carrier email address

This will ensure we're analyzing CHR→carrier trigger patterns, not customer→CHR inquiries.

In [ ]:
def filter_to_first_chr_response(df):
    """
    Filter emails in each conversation to only include messages up to and including 
    the first CHR response to external recipients.
    
    For each CONVERSATION_ID:
    1. Find the first TIME_SENT_UTC where:
       - SENDER_DOMAIN = 'chrobinson.com'
       - RECIPIENT_DOMAIN contains at least one non-CHR domain
    2. Keep only emails where TIME_SENT_UTC <= first CHR response time
    
    This isolates the initial email thread leading up to CHR's first external response.
    
    Args:
        df: DataFrame with CONVERSATION_ID, TIME_SENT_UTC, SENDER_DOMAIN, 
            and RECIPIENT_DOMAIN columns
        
    Returns:
        Filtered DataFrame containing only emails up to first CHR external response
    """
    import re
    
    original_count = len(df)
    
    def has_external_recipient(recipient_domain):
        """Check if RECIPIENT_DOMAIN contains at least one non-CHR domain."""
        if pd.isna(recipient_domain):
            return False
        
        # Handle list (actual or string representation)
        if isinstance(recipient_domain, list):
            domains = recipient_domain
        elif isinstance(recipient_domain, str):
            # Parse string representation of list
            if recipient_domain.strip().startswith('['):
                try:
                    import ast
                    domains = ast.literal_eval(recipient_domain)
                    if not isinstance(domains, list):
                        domains = [recipient_domain]
                except (ValueError, SyntaxError):
                    domains = [recipient_domain]
            else:
                domains = [recipient_domain]
        else:
            domains = [str(recipient_domain)]
        
        # Check if any domain is not chrobinson.com
        for domain in domains:
            if domain and str(domain).strip().lower() != 'chrobinson.com':
                return True
        return False
    
    print("="*80)
    print("📧 FILTERING TO FIRST CHR EXTERNAL RESPONSE")
    print("="*80)
    print(f"Original email count: {original_count:,}")
    print(f"Finding first CHR response to external recipients per conversation...")
    print("="*80 + "\n")
    
    # Find first CHR external response time for each conversation
    first_chr_response = {}
    
    for conv_id, group in df.groupby('CONVERSATION_ID'):
        # Filter to CHR senders with external recipients
        chr_external_emails = group[
            (group['SENDER_DOMAIN'] == 'chrobinson.com') &
            (group['RECIPIENT_DOMAIN'].apply(has_external_recipient))
        ]
        
        if len(chr_external_emails) > 0:
            # Get the minimum (first) TIME_SENT_UTC for CHR external responses
            first_time = chr_external_emails['TIME_SENT_UTC'].min()
            first_chr_response[conv_id] = first_time
    
    # Filter dataframe
    def should_keep_email(row):
        """Keep email if it's before or equal to first CHR external response."""
        conv_id = row['CONVERSATION_ID']
        
        # If no CHR external response found in this conversation, REMOVE it
        if conv_id not in first_chr_response:
            return False
        
        # Keep if email time <= first CHR response time
        return row['TIME_SENT_UTC'] <= first_chr_response[conv_id]
    
    df_filtered = df[df.apply(should_keep_email, axis=1)].copy()
    
    removed_count = original_count - len(df_filtered)
    conversations_with_chr_response = len(first_chr_response)
    total_conversations = df['CONVERSATION_ID'].nunique()
    conversations_removed = total_conversations - conversations_with_chr_response
    
    print("\n" + "="*80)
    print("📊 FILTERING SUMMARY")
    print("="*80)
    print(f"Total conversations in input: {total_conversations:,}")
    print(f"Conversations with CHR external response: {conversations_with_chr_response:,}")
    print(f"Conversations removed (no CHR external response): {conversations_removed:,}")
    print(f"\nEmails removed (after first CHR response or no response): {removed_count:,}")
    print(f"Emails remaining: {len(df_filtered):,}")
    print(f"Retention rate: {len(df_filtered)/original_count*100:.2f}%")
    print("="*80)
    
    return df_filtered

print("✅ Filter function created: filter_to_first_chr_response()")

✅ Filter function created: filter_to_first_chr_response()

In [ ]:
# Example: Apply the filter to get emails up to first CHR response
print("="*80)
print("📊 BEFORE FILTERING TO FIRST CHR RESPONSE")
print("="*80)
print(f"DataFrame shape: {df_final_filtered.shape}")
print(f"Total emails: {len(df_final_filtered):,}")
print(f"Total conversations: {df_final_filtered['CONVERSATION_ID'].nunique():,}")
print(f"Columns: {df_final_filtered.shape[1]}")
print("="*80 + "\n")

# Apply the filter
df_filtered_to_first_response = filter_to_first_chr_response(df_final_filtered)

print(f"\n{'='*80}")
print("📊 AFTER FILTERING TO FIRST CHR RESPONSE")
print("="*80)
print(f"DataFrame shape: {df_filtered_to_first_response.shape}")
print(f"Total emails: {len(df_filtered_to_first_response):,}")
print(f"Total conversations: {df_filtered_to_first_response['CONVERSATION_ID'].nunique():,}")
print(f"Columns: {df_filtered_to_first_response.shape[1]}")
print("="*80 + "\n")

print(f"{'='*80}")
print("📈 COMPARISON")
print("="*80)
print(f"Emails removed: {len(df_final_filtered) - len(df_filtered_to_first_response):,}")
print(f"Conversations removed: {df_final_filtered['CONVERSATION_ID'].nunique() - df_filtered_to_first_response['CONVERSATION_ID'].nunique():,}")
print(f"Email retention rate: {len(df_filtered_to_first_response)/len(df_final_filtered)*100:.2f}%")
print(f"Conversation retention rate: {df_filtered_to_first_response['CONVERSATION_ID'].nunique()/df_final_filtered['CONVERSATION_ID'].nunique()*100:.2f}%")
print("="*80 + "\n")

df_filtered_to_first_response.head()

================================================================================
📊 BEFORE FILTERING TO FIRST CHR RESPONSE
================================================================================
DataFrame shape: (466172, 34)
Total emails: 466,172
Total conversations: 168,654
Columns: 34
================================================================================

================================================================================
📧 FILTERING TO FIRST CHR EXTERNAL RESPONSE
================================================================================
Original email count: 466,172
Finding first CHR response to external recipients per conversation...
================================================================================


================================================================================
📊 FILTERING SUMMARY
================================================================================
Total conversations in input: 168,654
Conversations with CHR external response: 57,742
Conversations removed (no CHR external response): 110,912

Emails removed (after first CHR response or no response): 379,761
Emails remaining: 86,411
Retention rate: 18.54%
================================================================================

================================================================================
📊 AFTER FILTERING TO FIRST CHR RESPONSE
================================================================================
DataFrame shape: (86411, 34)
Total emails: 86,411
Total conversations: 57,742
Columns: 34
================================================================================

================================================================================
📈 COMPARISON
================================================================================
Emails removed: 379,761
Conversations removed: 110,912
Email retention rate: 18.54%

================================================================================
📊 FILTERING SUMMARY
================================================================================
Total conversations in input: 168,654
Conversations with CHR external response: 57,742
Conversations removed (no CHR external response): 110,912

Emails removed (after first CHR response or no response): 379,761
Emails remaining: 86,411
Retention rate: 18.54%
================================================================================

================================================================================
📊 AFTER FILTERING TO FIRST CHR RESPONSE
================================================================================
DataFrame shape: (86411, 34)
Total emails: 86,411
Total conversations: 57,742
Columns: 34
================================================================================

================================================================================
📈 COMPARISON
================================================================================
Emails removed: 379,761
Conversations removed: 110,912
Email retention rate: 18.54%
Conversation retention rate: 34.24%
================================================================================

Conversation retention rate: 34.24%
================================================================================

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,TIME_SENT_UTC,...,partycodes,carrier_code,carrier_name,match_count,match_source,CONVERSATION_ID_final,loadnumbers_final,partycodes_final,carrier_code_final,carrier_name_final
2,AAQkADJlY2Q3OTU3LTY0ZWQtNDAxNi1iYjdjLWRhMTY5Yz...,10c4e3fa-aa4d-40a0-93d0-97d73b05a2ae,RE: PO#23999450-SO#370822,IPCCHROperations@chrobinson.com,chrobinson.com,1,"[ ""IPCCHROperations@chrobinson.com"", ""dulope...","[ ""chrobinson.com"", ""onelineage.com""]","[ 0, 1]",2026-03-11 15:09:13.815541,...,[C8734892],T5160094,IIK TRANSPORT INC,1,body,AAQkADJlY2Q3OTU3LTY0ZWQtNDAxNi1iYjdjLWRhMTY5Yz...,[545560497],[C8734892],T5160094,IIK TRANSPORT INC
10,AAQkADMwMmYxMmEyLTYzYjYtNDU0My04MDRmLWYzNzk1Nj...,be721842-207a-42b3-8d02-aaaac94c0c6f,RE: HS-IN 4800147344/Hub & Spoke/CH Robinson,PrimeSourceSupport@chrobinson.com,chrobinson.com,1,"[ ""tuckerc@primesourcebp.com"", ""Lucas.Griffi...","[ ""primesourcebp.com"", ""chrobinson.com""]","[ 0, 1]",2026-03-26 13:50:09.391428,...,[C8710947],T5095847,"Nightline Express, Inc.",2,body,AAQkADMwMmYxMmEyLTYzYjYtNDU0My04MDRmLWYzNzk1Nj...,[548070611],[C8710947],T5095847,"Nightline Express, Inc."
11,AAQkADZlNTQ2YjdjLTVkY2ItNDZhOC1iNDUyLTU0OWE3Mj...,0c70bad9-4cdb-4074-8664-a120cab7277b,"RE: Oakwood, GA - 125346",Matthew.Miller4@chrobinson.com,chrobinson.com,1,"[ ""nikkic@noracadditives.com""]","[ ""noracadditives.com""]",[ 0],2026-04-14 16:02:48.928531,...,[C340804],T5303171,GP Transportation Co,1,subject,AAQkADZlNTQ2YjdjLTVkY2ItNDZhOC1iNDUyLTU0OWE3Mj...,[551193563],[C340804],T5303171,GP Transportation Co
14,AAQkADQwY2ZhNzRhLTY4YTYtNGM3YS04YzcyLTM3YTEyMz...,2422f4ee-988c-48dc-825d-0f8d5af6dbbd,LFD - BL# 541940579WAW/HLBU3228940/Reckitt Ben...,Kristina.Rice@chrobinson.com,chrobinson.com,1,"[ ""delivery.orders@aquila-88.com"", ""dispatch...","[ ""aquila-88.com""]",[ 0],2026-03-08 17:31:07.077055,...,[C8942714],T735179,K. & T. TRANSPORT LTD.,1,subject,AAQkADQwY2ZhNzRhLTY4YTYtNGM3YS04YzcyLTM3YTEyMz...,[552452382],[C8942714],T735179,K. & T. TRANSPORT LTD.
18,AAQkADg5ODMwZTZkLTQyZWYtNDkxOS05MmZhLTAxYTI3NW...,86d3f7c6-147e-435c-90e4-ce8cd4b73bc3,RE: CARGO TRACKING/C/DREAMSLEEP S/JUZHENG INTE...,CLTimp2@chrobinson.com,chrobinson.com,1,"[ ""ken@dreamsleephome.com"", ""Jonathan@fleisc...","[ ""fleischer-chb.com"", ""lead-trans.com"", ""d...","[ 1, 0]",2026-04-07 18:31:35.490735,...,[C8908532],T5002636,"Transportes Rivera Gonzalez, S.A. de C.V.",1,body,AAQkADg5ODMwZTZkLTQyZWYtNDkxOS05MmZhLTAxYTI3NW...,[541573431],[C8908532],T5002636,"Transportes Rivera Gonzalez, S.A. de C.V."

## 🔮 Future Enhancement: Filter to Carrier Communications Only

**Coming Soon** - Once carrier email identification data is available, add additional filtering here to isolate **only** CHR↔carrier communications.

### Recommended Approach:

```python
# Option 1: Filter by carrier email addresses
# If you have a list/set of known carrier email addresses
carrier_emails = set(['carrier1@example.com', 'carrier2@example.com', ...])

def has_carrier_involvement(row):
    """Check if email involves a carrier contact."""
    sender = row.get('SENDER', '')
    recipients = row.get('RECIPIENT_DOMAIN', [])
    
    # Check if sender is a carrier
    if sender in carrier_emails:
        return True
    
    # Check if any recipient is a carrier
    if isinstance(recipients, list):
        for recipient in recipients:
            if recipient in carrier_emails:
                return True
    
    return False

df_carrier_only = df_filtered_to_first_response[
    df_filtered_to_first_response.apply(has_carrier_involvement, axis=1)
]

# Option 2: Filter by carrier_code matches
# If emails are enriched with carrier_code from crosswalk
df_carrier_only = df_filtered_to_first_response[
    df_filtered_to_first_response['carrier_code'].notna()
]

# Option 3: Filter to CHR→carrier direction specifically
# Keep only emails where CHR is sender AND recipient is a carrier
df_chr_to_carrier = df_filtered_to_first_response[
    (df_filtered_to_first_response['SENDER_IS_CHR'] == 1) &
    (df_filtered_to_first_response.apply(lambda row: 
        any(email in carrier_emails for email in row.get('RECIPIENT', [])), axis=1))
]
```

This will ensure the analysis focuses on CHR→carrier trigger patterns, excluding customer→CHR inquiries.

This filters to emails that are only external emails sent by CHR sender

In [ ]:
def filter_chr_senders_only(df):
    """
    Filter to keep only emails sent by CHR domain senders.
    
    Keeps emails where:
    - SENDER_IS_CHR = 1 (CHR sender)
    
    Removes emails where:
    - SENDER_IS_CHR = 0 (non-CHR sender)
    
    Args:
        df: DataFrame with SENDER_IS_CHR column
        
    Returns:
        Filtered DataFrame with only CHR sender emails
    """
    original_count = len(df)
    
    # Keep only emails where sender is CHR (SENDER_IS_CHR = 1)
    df_filtered = df[df['SENDER_IS_CHR'] == 1].copy()
    
    removed_count = original_count - len(df_filtered)
    
    print("="*80)
    print("📧 CHR SENDER FILTERING")
    print("="*80)
    print(f"Original email count: {original_count:,}")
    print(f"Emails removed (non-CHR senders): {removed_count:,}")
    print(f"Emails remaining (CHR senders only): {len(df_filtered):,}")
    print(f"Retention rate: {len(df_filtered)/original_count*100:.2f}%")
    print("="*80)
    
    return df_filtered

print("✅ Filter function created: filter_chr_senders_only()")

✅ Filter function created: filter_chr_senders_only()

In [ ]:
# Apply the filter to keep only CHR sender emails
df_final_chr_only = filter_chr_senders_only(df_filtered_to_first_response) # df_final_filtered

print(f"\n✅ CHR-only sender dataframe created: df_final_chr_only")
print(f"Shape: {df_final_chr_only.shape}")

# Show filtering progression statistics
print(f"\n{'='*80}")
print(f"📊 FILTERING PROGRESSION SUMMARY")
print(f"{'='*80}")
print(f"Starting dataset (df_final): {len(df_final):,} emails")
print(f"\nAfter filter 1 (remove internal CHR emails): {len(df_final_filtered):,} emails")
print(f"  └─ Removed: {len(df_final) - len(df_final_filtered):,} emails ({(len(df_final) - len(df_final_filtered))/len(df_final)*100:.2f}%)")
print(f"\nAfter filter 2 (filter to first CHR response): {len(df_filtered_to_first_response):,} emails")
print(f"  └─ Removed: {len(df_final_filtered) - len(df_filtered_to_first_response):,} emails ({(len(df_final_filtered) - len(df_filtered_to_first_response))/len(df_final_filtered)*100:.2f}%)")
print(f"\nAfter filter 3 (keep only CHR senders): {len(df_final_chr_only):,} emails")
print(f"  └─ Removed: {len(df_filtered_to_first_response) - len(df_final_chr_only):,} emails ({(len(df_filtered_to_first_response) - len(df_final_chr_only))/len(df_filtered_to_first_response)*100:.2f}%)")
print(f"\n{'TOTAL FILTERING IMPACT:':-^80}")
print(f"Original emails: {len(df_final):,}")
print(f"Final emails: {len(df_final_chr_only):,}")
print(f"Total removed: {len(df_final) - len(df_final_chr_only):,} emails ({(len(df_final) - len(df_final_chr_only))/len(df_final)*100:.2f}%)")
print(f"Retention rate: {len(df_final_chr_only)/len(df_final)*100:.2f}%")
print(f"{'='*80}")

df_final_chr_only.head()

================================================================================
📧 CHR SENDER FILTERING
================================================================================
Original email count: 86,411
Emails removed (non-CHR senders): 28,669
Emails remaining (CHR senders only): 57,742
Retention rate: 66.82%
================================================================================

✅ CHR-only sender dataframe created: df_final_chr_only
Shape: (57742, 34)

================================================================================
📊 FILTERING PROGRESSION SUMMARY
================================================================================
Starting dataset (df_final): 494,317 emails

After filter 1 (remove internal CHR emails): 466,172 emails
  └─ Removed: 28,145 emails (5.69%)

After filter 2 (filter to first CHR response): 86,411 emails
  └─ Removed: 379,761 emails (81.46%)

After filter 3 (keep only CHR senders): 57,742 emails
  └─ Removed: 28,669 emails (33.18%)

----------------------------TOTAL FILTERING IMPACT:-----------------------------
Original emails: 494,317
Final emails: 57,742
Total removed: 436,575 emails (88.32%)
Retention rate: 11.68%
================================================================================

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,TIME_SENT_UTC,...,partycodes,carrier_code,carrier_name,match_count,match_source,CONVERSATION_ID_final,loadnumbers_final,partycodes_final,carrier_code_final,carrier_name_final
2,AAQkADJlY2Q3OTU3LTY0ZWQtNDAxNi1iYjdjLWRhMTY5Yz...,10c4e3fa-aa4d-40a0-93d0-97d73b05a2ae,RE: PO#23999450-SO#370822,IPCCHROperations@chrobinson.com,chrobinson.com,1,"[ ""IPCCHROperations@chrobinson.com"", ""dulope...","[ ""chrobinson.com"", ""onelineage.com""]","[ 0, 1]",2026-03-11 15:09:13.815541,...,[C8734892],T5160094,IIK TRANSPORT INC,1,body,AAQkADJlY2Q3OTU3LTY0ZWQtNDAxNi1iYjdjLWRhMTY5Yz...,[545560497],[C8734892],T5160094,IIK TRANSPORT INC
10,AAQkADMwMmYxMmEyLTYzYjYtNDU0My04MDRmLWYzNzk1Nj...,be721842-207a-42b3-8d02-aaaac94c0c6f,RE: HS-IN 4800147344/Hub & Spoke/CH Robinson,PrimeSourceSupport@chrobinson.com,chrobinson.com,1,"[ ""tuckerc@primesourcebp.com"", ""Lucas.Griffi...","[ ""primesourcebp.com"", ""chrobinson.com""]","[ 0, 1]",2026-03-26 13:50:09.391428,...,[C8710947],T5095847,"Nightline Express, Inc.",2,body,AAQkADMwMmYxMmEyLTYzYjYtNDU0My04MDRmLWYzNzk1Nj...,[548070611],[C8710947],T5095847,"Nightline Express, Inc."
11,AAQkADZlNTQ2YjdjLTVkY2ItNDZhOC1iNDUyLTU0OWE3Mj...,0c70bad9-4cdb-4074-8664-a120cab7277b,"RE: Oakwood, GA - 125346",Matthew.Miller4@chrobinson.com,chrobinson.com,1,"[ ""nikkic@noracadditives.com""]","[ ""noracadditives.com""]",[ 0],2026-04-14 16:02:48.928531,...,[C340804],T5303171,GP Transportation Co,1,subject,AAQkADZlNTQ2YjdjLTVkY2ItNDZhOC1iNDUyLTU0OWE3Mj...,[551193563],[C340804],T5303171,GP Transportation Co
14,AAQkADQwY2ZhNzRhLTY4YTYtNGM3YS04YzcyLTM3YTEyMz...,2422f4ee-988c-48dc-825d-0f8d5af6dbbd,LFD - BL# 541940579WAW/HLBU3228940/Reckitt Ben...,Kristina.Rice@chrobinson.com,chrobinson.com,1,"[ ""delivery.orders@aquila-88.com"", ""dispatch...","[ ""aquila-88.com""]",[ 0],2026-03-08 17:31:07.077055,...,[C8942714],T735179,K. & T. TRANSPORT LTD.,1,subject,AAQkADQwY2ZhNzRhLTY4YTYtNGM3YS04YzcyLTM3YTEyMz...,[552452382],[C8942714],T735179,K. & T. TRANSPORT LTD.
18,AAQkADg5ODMwZTZkLTQyZWYtNDkxOS05MmZhLTAxYTI3NW...,86d3f7c6-147e-435c-90e4-ce8cd4b73bc3,RE: CARGO TRACKING/C/DREAMSLEEP S/JUZHENG INTE...,CLTimp2@chrobinson.com,chrobinson.com,1,"[ ""ken@dreamsleephome.com"", ""Jonathan@fleisc...","[ ""fleischer-chb.com"", ""lead-trans.com"", ""d...","[ 1, 0]",2026-04-07 18:31:35.490735,...,[C8908532],T5002636,"Transportes Rivera Gonzalez, S.A. de C.V.",1,body,AAQkADg5ODMwZTZkLTQyZWYtNDkxOS05MmZhLTAxYTI3NW...,[541573431],[C8908532],T5002636,"Transportes Rivera Gonzalez, S.A. de C.V."

### ✅ Verification: One Email per Conversation

Verify that `df_final_chr_only` contains exactly **one email per conversation** - the first time a CHR employee reaches out to an external carrier.

This is the expected behavior because:
- **Filter 2** isolates emails up to the first CHR external response
- **Filter 3** keeps only CHR senders, which means only that first CHR response remains per conversation
- This ensures `carrier_recipients_sorted` analyzes the **initial CHR→carrier outreach**, not follow-up emails

In [ ]:
# Verify emails per conversation in df_final_chr_only
emails_per_conversation = df_final_chr_only.groupby('CONVERSATION_ID').size()

print("="*80)
print("✅ EMAILS PER CONVERSATION VERIFICATION (df_final_chr_only)")
print("="*80)
print(f"Total conversations: {len(emails_per_conversation):,}")
print(f"Total emails: {len(df_final_chr_only):,}")
print(f"Average emails per conversation: {emails_per_conversation.mean():.2f}")
print(f"\n{'VERIFICATION RESULT:':-^80}")

# Check if there's exactly 1 email per conversation
if emails_per_conversation.max() == 1 and emails_per_conversation.min() == 1:
    print("✅ CONFIRMED: Exactly 1 email per conversation")
    print(f"\nAll {len(emails_per_conversation):,} conversations have exactly 1 email.")
    print("\nThis means carrier_recipients_sorted analyzes:")
    print("  • The FIRST time a CHR employee reaches out to an external carrier")
    print("  • One data point per conversation (no duplicates)")
    print("  • Initial CHR→carrier outreach patterns only")
else:
    print("⚠️ WARNING: Multiple emails per conversation detected")
    print(f"\nConversations with exactly 1 email: {(emails_per_conversation == 1).sum():,} ({(emails_per_conversation == 1).sum()/len(emails_per_conversation)*100:.2f}%)")
    print(f"Conversations with 2+ emails: {(emails_per_conversation > 1).sum():,} ({(emails_per_conversation > 1).sum()/len(emails_per_conversation)*100:.2f}%)")
    print(f"Max emails in a conversation: {emails_per_conversation.max()}")
    
    print(f"\n{'Distribution of emails per conversation:':-^80}")
    conversation_dist = emails_per_conversation.value_counts().sort_index()
    for num_emails, count in conversation_dist.head(10).items():
        pct = (count / len(emails_per_conversation)) * 100
        print(f"  {num_emails} email(s): {count:,} conversations ({pct:.2f}%)")

print("="*80)

================================================================================
📊 EMAILS PER CONVERSATION ANALYSIS (df_final_chr_only)
================================================================================
Total conversations: 57,742
Total emails: 57,742
Average emails per conversation: 1.00
Median emails per conversation: 1
Max emails in a conversation: 1

Conversations with exactly 1 email: 57,742 (100.00%)
Conversations with 2+ emails: 0 (0.00%)

--------------------Distribution of emails per conversation:--------------------
  1 email(s): 57,742 conversations (100.00%)
================================================================================

## 5. Analyze Non-CHR Email Recipients by Carrier

Analyze which external email addresses each carrier communicates with and the distribution of emails sent to each recipient.

In [ ]:
def analyze_carrier_recipients(df):
    """
    Analyze non-CHR email recipients by carrier code.
    
    For each carrier, this function:
    1. Extracts all recipient email addresses from the RECIPIENT field
    2. Filters to only non-CHR emails (not ending in @chrobinson.com)
    3. Calculates the percentage of emails sent to each non-CHR recipient
    
    Args:
        df: DataFrame with CARRIER_CODE and RECIPIENT columns
        
    Returns:
        DataFrame with columns:
        - carrier_code: The carrier code
        - non_chr_recipients: Array of non-CHR email addresses
        - recipient_percentages: Array of percentages (corresponding to non_chr_recipients)
    """
    import re
    from collections import Counter
    
    def extract_non_chr_emails(recipient_field):
        """Extract non-CHR email addresses from the RECIPIENT field."""
        if pd.isna(recipient_field) or recipient_field == '':
            return []
        
        # Extract all email addresses using regex
        email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
        emails = re.findall(email_pattern, str(recipient_field))
        
        # Filter to only non-CHR emails (not ending in @chrobinson.com)
        non_chr_emails = [
            email.lower() for email in emails 
            if not email.lower().endswith('@chrobinson.com')
        ]
        
        return non_chr_emails
    
    # Filter to only rows with carrier_code
    df_with_carrier = df[df['carrier_code'].notna()].copy()
    
    print("="*80)
    print("📊 ANALYZING NON-CHR RECIPIENTS BY CARRIER")
    print("="*80)
    print(f"Total emails with carrier code: {len(df_with_carrier):,}")
    print(f"Processing recipient email extraction...")
    print("="*80 + "\n")
    
    # Group by carrier_code and analyze recipients
    results = []
    
    for carrier_code, group in df_with_carrier.groupby('carrier_code'):
        # Get carrier_name (should be the same for all rows in group)
        carrier_name = group['carrier_name'].iloc[0] if 'carrier_name' in group.columns else None
        
        # Count all non-CHR emails for this carrier
        all_non_chr_emails = []
        
        for _, row in group.iterrows():
            non_chr_emails = extract_non_chr_emails(row['RECIPIENT'])
            all_non_chr_emails.extend(non_chr_emails)
        
        if len(all_non_chr_emails) == 0:
            # No non-CHR recipients for this carrier
            continue
        
        # Count occurrences of each email
        email_counts = Counter(all_non_chr_emails)
        total_emails = len(all_non_chr_emails)
        
        # Sort by count (descending) to get most common recipients first
        sorted_emails = sorted(email_counts.items(), key=lambda x: x[1], reverse=True)
        
        # Extract emails and percentages in the same order
        non_chr_recipients = [email for email, count in sorted_emails]
        recipient_percentages = [
            round((count / total_emails) * 100, 2) 
            for email, count in sorted_emails
        ]
        
        results.append({
            'carrier_code': carrier_code,
            'carrier_name': carrier_name,
            'non_chr_recipients': non_chr_recipients,
            'recipient_percentages': recipient_percentages,
            'total_non_chr_emails': total_emails,
            'unique_recipients': len(non_chr_recipients)
        })
    
    # Create result dataframe
    result_df = pd.DataFrame(results)
    
    # Sort by total_non_chr_emails descending
    result_df = result_df.sort_values('total_non_chr_emails', ascending=False).reset_index(drop=True)
    
    print("\n" + "="*80)
    print("📈 ANALYSIS SUMMARY")
    print("="*80)
    print(f"Carriers with non-CHR recipients: {len(result_df):,}")
    print(f"Total non-CHR email instances analyzed: {result_df['total_non_chr_emails'].sum():,}")
    print(f"\nTop 5 carriers by non-CHR email volume:")
    for i, row in result_df.head().iterrows():
        carrier_display = f"{row['carrier_code']}"
        if pd.notna(row.get('carrier_name')):
            carrier_display += f" ({row['carrier_name']})"
        print(f"  {i+1}. {carrier_display}: {row['total_non_chr_emails']:,} emails to {row['unique_recipients']} unique recipients")
    print("="*80)
    
    return result_df

print("✅ Carrier recipient analysis function created: analyze_carrier_recipients()")

✅ Carrier recipient analysis function created: analyze_carrier_recipients()

In [ ]:
df_final_filtered.columns

Index(['CONVERSATION_ID', 'MESSAGE_ID', 'SUBJECT', 'SENDER', 'SENDER_DOMAIN',
       'SENDER_IS_CHR', 'RECIPIENT', 'RECIPIENT_DOMAIN', 'RECIPIENT_IS_CHR',
       'TIME_SENT_UTC', 'SENT_DATE', 'SENT_HOUR', 'TIME_RECEIVED_UTC',
       'MAILBOXES', 'CLASSIFICATION', 'CATEGORIES', 'MONTHSTARTDATE',
       'WORKDAYS', 'EMAIL_TEXT_CLEAN', 'extracted_ids_subject',
       'extracted_ids_body', 'extracted_identifiers', 'matched_refnums',
       'loadnumbers', 'partycodes', 'carrier_code', 'carrier_name',
       'match_count', 'match_source', 'CONVERSATION_ID_final',
       'loadnumbers_final', 'partycodes_final', 'carrier_code_final',
       'carrier_name_final'],
      dtype='object')

In [ ]:
# df_final_filtered.to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/final_filtered_emails.csv', index=False)

In [ ]:
# Analyze non-CHR recipients by carrier
carrier_recipients_df = analyze_carrier_recipients(df_final_chr_only)

print(f"\n✅ Analysis complete!")
print(f"\nResult dataframe columns:")
print(f"  - carrier_code: Carrier identifier")
print(f"  - carrier_name: Carrier name")
print(f"  - non_chr_recipients: Array of non-CHR email addresses (sorted by frequency)")
print(f"  - recipient_percentages: Percentage of emails to each recipient (same order)")
print(f"  - total_non_chr_emails: Total number of non-CHR email instances")
print(f"  - unique_recipients: Count of unique non-CHR recipients")

carrier_recipients_df.head()

================================================================================
📊 ANALYZING NON-CHR RECIPIENTS BY CARRIER
================================================================================
Total emails with carrier code: 36,235
Processing recipient email extraction...
================================================================================

================================================================================
📈 ANALYSIS SUMMARY
================================================================================
Carriers with non-CHR recipients: 7,380
Total non-CHR email instances analyzed: 83,536

Top 5 carriers by non-CHR email volume:
  1. T5002636 (Transportes Rivera Gonzalez, S.A. de C.V.): 3,383 emails to 2726 unique recipients
  2. T191369 (Werner Enterprises, Inc.  ( Dedicated)): 2,259 emails to 177 unique recipients
  3. T2081243 (ROBERT L GAST INC): 2,137 emails to 413 unique recipients
  4. T1098838 (Auto Express Frontera Norte S.A. de C.V.): 1,821 emails to 954 unique recipients
  5. T6311362 (TIMEIT LOGISTICS LLC): 1,819 emails to 335 unique recipients
================================================================================

✅ Analysis complete!

Result dataframe columns:
  - carrier_code: Carrier identifier
  - carrier_name: Carrier name
  - non_chr_recipients: Array of non-CHR email addresses (sorted by frequency)
  - recipient_percentages: Percentage of emails to each recipient (same order)
  - total_non_chr_emails: Total number of non-CHR email instances
  - unique_recipients: Count of unique non-CHR recipients

,carrier_code,carrier_name,non_chr_recipients,recipient_percentages,total_non_chr_emails,unique_recipients
0,T5002636,"Transportes Rivera Gonzalez, S.A. de C.V.","[jcartia@peltonshepherd.com, amber.murphy@inte...","[0.83, 0.3, 0.27, 0.27, 0.27, 0.27, 0.24, 0.24...",3383,2726
1,T191369,"Werner Enterprises, Inc. ( Dedicated)","[optimizationah@werner.com, austin.woerdehoff@...","[26.52, 11.73, 11.6, 11.55, 2.39, 1.73, 1.73, ...",2259,177
2,T2081243,ROBERT L GAST INC,"[chrtracking@superegoholding.net, dispatch@rob...","[16.24, 13.48, 8.89, 8.0, 2.57, 1.73, 1.73, 1....",2137,413
3,T1098838,Auto Express Frontera Norte S.A. de C.V.,"[naecustomerservice@saia.com, karen.barnes@odf...","[1.32, 1.32, 1.26, 1.21, 1.21, 1.1, 1.1, 1.04,...",1821,954
4,T6311362,TIMEIT LOGISTICS LLC,"[chrtracking@superegoholding.net, dispatch@tim...","[22.48, 12.64, 10.61, 8.3, 7.7, 5.66, 5.0, 0.7...",1819,335

### Example: View Top Recipients for a Specific Carrier

Let's examine the distribution of recipients for one carrier in detail.

In [ ]:
# Example: View details for the carrier with the most non-CHR emails
if len(carrier_recipients_df) > 0:
    top_carrier = carrier_recipients_df.iloc[0]
    
    print("="*80)
    carrier_display = f"📧 CARRIER: {top_carrier['carrier_code']}"
    if pd.notna(top_carrier.get('carrier_name')):
        carrier_display += f" ({top_carrier['carrier_name']})"
    print(carrier_display)
    print("="*80)
    print(f"Total non-CHR emails: {top_carrier['total_non_chr_emails']:,}")
    print(f"Unique recipients: {top_carrier['unique_recipients']}")
    print(f"\nTop 10 Recipients (sorted by percentage):")
    print("-"*80)
    
    for i, (email, pct) in enumerate(zip(
        top_carrier['non_chr_recipients'][:10], 
        top_carrier['recipient_percentages'][:10]
    ), 1):
        print(f"{i:2d}. {email:50s} {pct:6.2f}%")
    
    print("="*80)
else:
    print("No carriers with non-CHR recipients found.")

================================================================================
📧 CARRIER: T5002636 (Transportes Rivera Gonzalez, S.A. de C.V.)
================================================================================
Total non-CHR emails: 3,383
Unique recipients: 2726

Top 10 Recipients (sorted by percentage):
--------------------------------------------------------------------------------
 1. jcartia@peltonshepherd.com                           0.83%
 2. amber.murphy@intellitrans.com                        0.30%
 3. rpettit@ldklogistics.com                             0.27%
 4. secgoinsidesales@delta.com                           0.27%
 5. irena.mustedanagic00@delta.com                       0.27%
 6. sergio.sanchez@doleintl.com                          0.27%
 7. dcitydispatch@odfl.com                               0.24%
 8. diana.vara@doleintl.com                              0.24%
 9. carrieta@hvac.mea.com                                0.21%
10. khiralal@cardinalcorp.com                            0.18%
================================================================================

### Identify Carriers with High Email Concentration

Sort carriers by the percentage of emails going to their top recipient to find carriers that send most emails to a single inbox.

In [ ]:
# Sort carriers by the percentage going to their top recipient (first value in recipient_percentages)
# This shows carriers with high email concentration to a single inbox

carrier_recipients_sorted = carrier_recipients_df.copy()

# Extract the first percentage (top recipient percentage) for sorting
carrier_recipients_sorted['top_recipient_pct'] = carrier_recipients_sorted['recipient_percentages'].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else 0
)

# Sort by top recipient percentage descending
carrier_recipients_sorted = carrier_recipients_sorted.sort_values('top_recipient_pct', ascending=False).reset_index(drop=True)

print("="*80)
print("📊 CARRIERS SORTED BY EMAIL CONCENTRATION TO TOP RECIPIENT")
print("="*80)
print(f"Total carriers analyzed: {len(carrier_recipients_sorted):,}\n")
print("Top 20 carriers with highest concentration to single recipient:")
print("-"*80)
print(f"{'#':<4} {'Carrier':<15} {'Carrier Name':<25} {'Top %':<8} {'Top Recipient Email':<30}")
print("-"*80)

for i, row in carrier_recipients_sorted.head(20).iterrows():
    carrier = str(row['carrier_code'])[:14]  # Truncate if too long
    carrier_name = str(row.get('carrier_name', ''))[:24] if pd.notna(row.get('carrier_name')) else ''
    top_pct = row['top_recipient_pct']
    top_email = row['non_chr_recipients'][0] if len(row['non_chr_recipients']) > 0 else 'N/A'
    top_email_display = top_email[:29] if len(top_email) > 29 else top_email
    
    print(f"{i+1:<4} {carrier:<15} {carrier_name:<25} {top_pct:>6.2f}%  {top_email_display}")

print("="*80)

# Display the full dataframe sorted
carrier_recipients_sorted

================================================================================
📊 CARRIERS SORTED BY EMAIL CONCENTRATION TO TOP RECIPIENT
================================================================================
Total carriers analyzed: 7,380

Top 20 carriers with highest concentration to single recipient:
--------------------------------------------------------------------------------
#    Carrier         Carrier Name              Top %    Top Recipient Email
--------------------------------------------------------------------------------
1    T5246772        Infinity Carriers Inc     100.00%  kdevarakonda@nextpower.com
2    T6299641        BUCKNER TRUCKING LLC      100.00%  bucknertrucking7@gmail.com
3    T6266141        KINGS AUTO AVE TRANSPORT  100.00%  emily_morton-lercher@ryder.co
4    T5196521        Alejandro Alegria Arias   100.00%  qfon_receiving@qualitycustomd
5    T6266359        BK LOGISTICS INC          100.00%  dispatchbklogs@gmail.com
6    T6299440        MATADORX LLC              100.00%  carlosg@kwrs.com
7    T6299481        DSL LOGISTIXS LLC         100.00%  orderadmin@roku.com
8    T6299538        COLETRANE SOLUTIONS LLC   100.00%  business@coletranesolutions.c
9    T5243192        BSL Express Trucking Inc  100.00%  carlene.coleman@bp.com
10   T4880442        FELIPE S NOVA             100.00%  novaaf0411@hotmail.com
11   T6299995        WIDE TRANSPORT INC        100.00%  vasquezj@primesourcebp.com
12   T6300285        WP LOGISTICS LLC          100.00%  shipmentstatus@uberfreight.co
13   T6300488        DSB LEGACY TRANS INC      100.00%  usa-appts.waterloo@refresco.c
14   T6300528        DESIGNED BY DOM LLC       100.00%  freightlogistics@icebrix.com
15   T6300537        TREE HOUSE TRUCKING LLC   100.00%  raycharles28008@gmail.com
16   T6300700        SOTO'S ROOFING & FLOORIN  100.00%  jared.cantalope@daktronics.co
17   T6031294        ABRON TRUCKING LLC        100.00%  nick.coronado@prolineproducts
18   T6026393        TEN-EIGHT INC             100.00%  eddie.j.thomas@p66.com
19   T6300871        SMART FREIGHT SOLUTIONS   100.00%  factoringar@truckstop.com
20   T4861042        ESKENDER USSO             100.00%  stocco@igps.net
================================================================================

,carrier_code,carrier_name,non_chr_recipients,recipient_percentages,total_non_chr_emails,unique_recipients,top_recipient_pct
0,T5246772,Infinity Carriers Inc,[kdevarakonda@nextpower.com],[100.0],1,1,100.00
1,T6299641,BUCKNER TRUCKING LLC,[bucknertrucking7@gmail.com],[100.0],1,1,100.00
2,T6266141,KINGS AUTO AVE TRANSPORT LLC,[emily_morton-lercher@ryder.com],[100.0],1,1,100.00
3,T5196521,Alejandro Alegria Arias,[qfon_receiving@qualitycustomdistribution.com],[100.0],1,1,100.00
4,T6266359,BK LOGISTICS INC,[dispatchbklogs@gmail.com],[100.0],1,1,100.00
...,...,...,...,...,...,...,...
7375,T4817985,EARLY TRUCKING COMPANY INC.,"[elizabeth.cruz@dsv.com, jason.dixon@4tsl.com,...","[1.55, 0.78, 0.78, 0.78, 0.78, 0.78, 0.78, 0.7...",516,424,1.55
7376,T5638,Brown Trucking Company,"[csi@emergemarket.com, mhelm@emergemarket.com,...","[1.36, 1.36, 1.36, 1.36, 0.91, 0.91, 0.91, 0.9...",220,200,1.36
7377,T5166447,Orozco Trucking Inc,"[rodneyspencer123@gmail.com, asadaspencer@gmai...","[1.33, 1.33, 0.95, 0.95, 0.95, 0.95, 0.95, 0.9...",527,340,1.33
7378,T1098838,Auto Express Frontera Norte S.A. de C.V.,"[naecustomerservice@saia.com, karen.barnes@odf...","[1.32, 1.32, 1.26, 1.21, 1.21, 1.1, 1.1, 1.04,...",1821,954,1.32
7379,T5002636,"Transportes Rivera Gonzalez, S.A. de C.V.","[jcartia@peltonshepherd.com, amber.murphy@inte...","[0.83, 0.3, 0.27, 0.27, 0.27, 0.27, 0.24, 0.24...",3383,2726,0.83

In [58]:
carrier_recipients_sorted.to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/carrier_recipient_analysis_CHR_first_response.csv', index=False)

## 🤖 AI Automation Candidate Identification

Identify carriers that are **ideal candidates for automated AI agent outreach** based on:
1. **High communication frequency** - CHR reaches out to them often
2. **High concentration** - Most communications go to the same recipient
3. **Consistency** - Predictable patterns suitable for automation

The goal: When a tracking request is received for these carriers, the AI agent can automatically reach out to the known contact.

In [ ]:
# Filter carriers that are good candidates for AI automation
# Criteria:
# 1. High frequency: Minimum number of tracking communications (adjust threshold as needed)
# 2. High concentration: Top recipient gets high % of emails (adjust threshold as needed)
# 3. Sufficient volume: Enough data to trust the pattern

# Configurable thresholds
MIN_TOTAL_EMAILS = 10        # Minimum total communications to consider
MIN_TOP_RECIPIENT_PCT = 70.0  # Minimum % going to top recipient
MIN_UNIQUE_RECIPIENTS = 1     # Ensure at least 1 recipient exists

# Apply filters
ai_automation_candidates = carrier_recipients_sorted[
    (carrier_recipients_sorted['total_non_chr_emails'] >= MIN_TOTAL_EMAILS) &
    (carrier_recipients_sorted['top_recipient_pct'] >= MIN_TOP_RECIPIENT_PCT) &
    (carrier_recipients_sorted['unique_recipients'] >= MIN_UNIQUE_RECIPIENTS)
].copy()

# Add additional useful columns
ai_automation_candidates['top_recipient_email'] = ai_automation_candidates['non_chr_recipients'].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else None
)

# Calculate confidence score (combination of frequency and concentration)
# Higher score = better automation candidate
ai_automation_candidates['automation_confidence_score'] = (
    (ai_automation_candidates['top_recipient_pct'] / 100) *  # Concentration weight (0-1)
    (ai_automation_candidates['total_non_chr_emails'].apply(lambda x: min(x / 100, 1)))  # Frequency weight (capped at 1)
) * 100  # Scale to 0-100

# Sort by confidence score
ai_automation_candidates = ai_automation_candidates.sort_values(
    'automation_confidence_score', 
    ascending=False
).reset_index(drop=True)

# Display results
print("="*80)
print("🤖 AI AUTOMATION CANDIDATES - HIGH FREQUENCY & HIGH CONCENTRATION")
print("="*80)
print(f"\n📊 Filtering Criteria:")
print(f"  • Minimum total emails: {MIN_TOTAL_EMAILS}")
print(f"  • Minimum top recipient %: {MIN_TOP_RECIPIENT_PCT}%")
print(f"  • Minimum unique recipients: {MIN_UNIQUE_RECIPIENTS}")
print(f"\n✅ Results:")
print(f"  • Total carriers analyzed: {len(carrier_recipients_sorted):,}")
print(f"  • Carriers meeting criteria: {len(ai_automation_candidates):,}")
print(f"  • Automation coverage: {len(ai_automation_candidates)/len(carrier_recipients_sorted)*100:.1f}%")

if len(ai_automation_candidates) > 0:
    print(f"\n{'TOP 20 AUTOMATION CANDIDATES (by confidence score):':-^80}")
    print(f"{'#':<4} {'Carrier':<12} {'Total':<7} {'Top%':<7} {'Confidence':<11} {'Top Recipient Email':<35}")
    print("-"*80)
    
    for idx, row in ai_automation_candidates.head(20).iterrows():
        carrier = str(row['carrier_code'])[:11]
        total = row['total_non_chr_emails']
        top_pct = row['top_recipient_pct']
        confidence = row['automation_confidence_score']
        email = str(row['top_recipient_email'])[:34] if pd.notna(row['top_recipient_email']) else 'N/A'
        
        print(f"{idx+1:<4} {carrier:<12} {total:<7} {top_pct:>5.1f}%  {confidence:>6.1f}/100   {email}")
    
    print("="*80)
    
    # Summary statistics
    print(f"\n📈 Summary Statistics:")
    print(f"  • Average emails per automation candidate: {ai_automation_candidates['total_non_chr_emails'].mean():.1f}")
    print(f"  • Average top recipient %: {ai_automation_candidates['top_recipient_pct'].mean():.1f}%")
    print(f"  • Average confidence score: {ai_automation_candidates['automation_confidence_score'].mean():.1f}")
    print(f"  • Median unique recipients: {ai_automation_candidates['unique_recipients'].median():.0f}")
else:
    print(f"\n⚠️ No carriers meet the current criteria. Consider adjusting thresholds.")

print("="*80)

In [ ]:
# Export automation candidates for AI agent configuration
if len(ai_automation_candidates) > 0:
    # Create a simplified export for AI agent configuration
    ai_agent_config = ai_automation_candidates[[
        'carrier_code',
        'carrier_name',
        'top_recipient_email',
        'top_recipient_pct',
        'total_non_chr_emails',
        'automation_confidence_score',
        'unique_recipients'
    ]].copy()
    
    # Save to CSV
    output_path = '/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/ai_automation_candidates.csv'
    ai_agent_config.to_csv(output_path, index=False)
    
    print(f"✅ Saved {len(ai_agent_config)} automation candidates to:")
    print(f"   {output_path}")
    
    # Display first few for verification
    print(f"\n📋 Sample AI Agent Configuration (first 10):")
    print(ai_agent_config.head(10).to_string(index=False))
else:
    print("⚠️ No automation candidates to export")

ai_automation_candidates.head(20)

### 💡 Recommendations for Workflow Enhancement

Based on your AI automation goal, here are recommendations to strengthen your analysis:

#### ✅ **Current Strengths:**
1. **Clean data pipeline** - Filters to first CHR external response (perfect for automation triggers)
2. **One email per conversation** - No duplicates, clean training data
3. **Concentration analysis** - Already identifies high-concentration carriers
4. **Frequency tracking** - Total emails per carrier captured

#### 🎯 **Additional Enhancements to Consider:**

1. **Time-based patterns:**
   - Add analysis of time-of-day/day-of-week when CHR reaches out
   - Identify if certain carriers are contacted at specific times
   - **Why:** AI agent can send at optimal times

2. **Response rate tracking** (if you add carrier email identification later):
   - Track which carriers respond and how quickly
   - Calculate response rates per carrier/recipient
   - **Why:** Prioritize automation for responsive carriers

3. **Load/shipment metadata enrichment:**
   - Add shipment type, lane, or service level data
   - Identify if specific recipient emails handle specific types of loads
   - **Why:** AI agent can route to the right specialist contact

4. **Threshold tuning:**
   - Current defaults: 10+ emails, 70%+ concentration
   - **Consider testing:** 5+ emails, 80%+ concentration for higher confidence
   - **Monitor:** How thresholds affect coverage vs. accuracy

5. **Multi-contact handling:**
   - For carriers with 2-3 frequent recipients (e.g., 40%, 35%, 25% split)
   - Add logic to try primary, then secondary if no response
   - **Why:** Increases automation success rate

6. **Confidence score refinement:**
   - Current: `(concentration * frequency_weight) * 100`
   - **Consider adding:** Recency weight (prefer recent patterns), consistency over time
   - **Why:** Ensures patterns are still valid

#### 📊 **Quick Wins for AI Implementation:**

**High Confidence (>80% concentration, 20+ emails):**
- Deploy AI agent immediately
- Full automation with human oversight

**Medium Confidence (70-80% concentration, 10-20 emails):**
- AI suggests recipient, human approves
- Semi-automated workflow

**Low Confidence (<70% concentration):**
- Human selects from top 3 recipients
- AI learns from selections

#### 🔄 **Continuous Improvement:**
- Re-run this analysis monthly/quarterly
- Track AI agent success rates
- Adjust thresholds based on real-world performance
- Remove carriers if patterns change

Possible ways to expand analysis

For emails that were sent by non CHR people, take the sender of that email and analyze if the sender is from the carrier or the customer.  (Somehow need to determine logic to know if the email is related to the customer or the carrier)