In [45]:
import pandas as pd
import numpy as np
from pathlib import Path
import logging
import sys

# Clear any existing handlers to prevent duplicates
root_logger = logging.getLogger()
if root_logger.handlers:
    for handler in root_logger.handlers:
        root_logger.removeHandler(handler)

# Configure logging FIRST before importing DataLoader
logging.basicConfig(level=logging.WARNING, force=True)

# Suppress specific loggers that are verbose
for logger_name in ['__main__', 'snowflake', 'azure', 'urllib3']:
    logging.getLogger(logger_name).setLevel(logging.WARNING)

# Add the project root to the path to import custom modules
project_root = Path.cwd().parent
sys.path.insert(0, str(project_root))

# Import the DataLoader class
from scripts.data_preparation.load import DataLoader

print("✓ Libraries imported successfully")
print("✓ Logging configured (INFO messages suppressed)")

✓ Libraries imported successfully
✓ Logging configured (INFO messages suppressed)

In [46]:
# Getting email data from startdate to enddate
startdate = '2026-04-01'
enddate = '2026-05-06'

print(f"Tracking Email History will be Retrieved from {startdate} to {enddate}")

Tracking Email History will be Retrieved from 2026-04-01 to 2026-05-06

## 1. Load Tracking Email Data from Snowflake

Load the tracking email data from Snowflake using the DataLoader class.

In [47]:
# Execute the query to get historical load data
print("Querying Snowflake for Tracking Email data...")
print(f"Date Range: {startdate} to {enddate}")

loader = DataLoader()

df = loader.load_from_snowflake(
    sql_file_path='../sql/EmailExtractionToContextBuilder.sql',
    params={'startdate': startdate, 'enddate': enddate}
)

print(f"\n✓ Loaded {len(df):,} rows from Snowflake")
print(f"  Date range in data: {df['SENT_DATE'].min()} to {df['SENT_DATE'].max()}")
print(f"  Columns: {len(df.columns)}")
df.head()

Querying Snowflake for Tracking Email data...
Date Range: 2026-04-01 to 2026-05-06

/home/azureuser/trackingContextBuilder/trackingContextBuilder/scripts/data_preparation/load.py:160: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.snowflake_conn)

✓ Loaded 237,890 rows from Snowflake
  Date range in data: 2026-04-01 to 2026-05-06
  Columns: 19

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,EMAIL_TEXT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,TIME_SENT_UTC,SENT_DATE,SENT_HOUR,TIME_RECEIVED_UTC,MAILBOXES,CLASSIFICATION,CATEGORIES,MONTHSTARTDATE,WORKDAYS
0,AAQkADZhOGU5MzE4LWZkYjYtNDE2YS1hMzg2LWQ1Yjk0OG...,dc732fe6-3506-4f43-a014-904cdd03e13e,FORVIA MTY_FAUM0416OT2 MX 549993775 // XB 5499...,"<html><head>\r\n<meta http-equiv=""Content-Type...",Diana.Gonzalez@chrobinson.com,chrobinson.com,1,"[\n ""edgarjavier.castillo@forvia.com"",\n ""va...","[\n ""buckland.com"",\n ""motherson.com"",\n ""e...","[\n 0,\n 1\n]",2026-04-15 19:40:42.968064,2026-04-15,19,2026-04-15 19:40:42,"[\n {\n ""EmailId"": """",\n ""MailboxId"": ""...",tracking-request,[],2026-04-01,22
1,AAQkADZmNDg3YzJlLTUwODgtNDAwNi1iNGM5LTU3ZmZiY2...,94c882ee-357f-40eb-8d32-caab7cf1caad,Re: FW: Need ETA,"<html><head>\r\n<meta http-equiv=""Content-Type...",nhaley@arrivelogistics.com,arrivelogistics.com,0,"[\n ""BenjaminMooreTeam@chrobinson.com""\n]","[\n ""chrobinson.com""\n]",[\n 1\n],2026-04-16 15:56:40.051615,2026-04-16,15,2026-04-16 15:56:39,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",tracking-request,[],2026-04-01,22
2,AAQkADQzOTE2ZmNmLTMxNTQtNDNhOC1hMzkzLWUyNjMzOG...,f61e7c86-ffc6-4e5f-bde5-2f4f70cd43bb,RE: Burgess load ETA,"<html><head>\r\n<meta http-equiv=""Content-Type...",tedpawlak@dar-techinc.com,dar-techinc.com,0,"[\n ""kschneider@dar-techinc.com"",\n ""Chris.P...","[\n ""chrobinson.com"",\n ""dar-techinc.com""\n]","[\n 1,\n 0\n]",2026-04-06 17:29:51.560843,2026-04-06,17,2026-04-06 17:29:51,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",tracking-request,[],2026-04-01,22
3,AAQkAGVlMTYxMTk0LTM1ZTktNGEwNy05MTMzLWM5MWRlMz...,a3eecc4f-5ff3-496e-9d53-35760704ebfc,Re: Need Driver Information for 550503524,"<html><head>\r\n<meta http-equiv=""Content-Type...",dispatch.support@munisatrans.com,munisatrans.com,0,"[\n ""Giovanni.Tregembo@chrobinson.com"",\n ""d...","[\n ""munisatrans.com"",\n ""chrobinson.com""\n]","[\n 0,\n 1\n]",2026-04-20 17:09:18.408981,2026-04-20,17,2026-04-20 17:09:18,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",carrier-tracking,[],2026-04-01,22
4,AAQkAGU2NDNmYjVlLWQxZjAtNGE5MS1hNzMzLTQ0Njc4ZD...,d2d34405-057c-4c5f-967f-a5fe67cded3f,RE: Inform Pull ECD15010023 order# 8142887801...,"<html><head>\r\n<meta http-equiv=""Content-Type...",kaiyi.zhang@hou-ep.fii-na.com,hou-ep.fii-na.com,0,"[\n ""hou2.logistics@hou-ep.fii-na.com"",\n ""J...","[\n ""chrobinson.com"",\n ""dsv.com"",\n ""delta...","[\n 0,\n 1\n]",2026-04-09 14:16:53.153544,2026-04-09,14,2026-04-09 14:16:52,"[\n {\n ""EmailId"": ""AAkALgAAAAAAHYQDEapmEc...",tracking-request,[],2026-04-01,22

In [48]:
# Creating UDF to remove \n from dictionary columns
def remove_characters(col: str | None) -> str:
    """Remove newline characters from string values.
    
    Args:
        col: Input string value

    Returns:
        String with newline characters removed
    """
    if col is None or pd.isna(col):
        return ''
    return str(col).replace('\n','')

In [49]:
object_cols = df.select_dtypes(include=['object']).columns.tolist()

In [50]:
for col in object_cols:
    print('Removing Characters for ', col)
    df[col] = df[col].apply(remove_characters)

Removing Characters for  CONVERSATION_ID

Removing Characters for  MESSAGE_ID
Removing Characters for  SUBJECT
Removing Characters for  SUBJECT
Removing Characters for  EMAIL_TEXT
Removing Characters for  EMAIL_TEXT
Removing Characters for  SENDER
Removing Characters for  SENDER_DOMAIN
Removing Characters for  SENDER
Removing Characters for  SENDER_DOMAIN
Removing Characters for  RECIPIENT
Removing Characters for  RECIPIENT_DOMAIN
Removing Characters for  RECIPIENT
Removing Characters for  RECIPIENT_DOMAIN
Removing Characters for  RECIPIENT_IS_CHR
Removing Characters for  SENT_DATE
Removing Characters for  RECIPIENT_IS_CHR
Removing Characters for  SENT_DATE
Removing Characters for  MAILBOXES
Removing Characters for  MAILBOXES
Removing Characters for  CLASSIFICATION
Removing Characters for  CATEGORIES
Removing Characters for  CLASSIFICATION
Removing Characters for  CATEGORIES
Removing Characters for  MONTHSTARTDATE
Removing Characters for  MONTHSTARTDATE

## 2. Load Tracking Identifier Crosswalk Data from Snowflake

This will allow mapping of emails back to individual Ccodes

In [51]:
# Execute the query to get historical load data
print("Querying Snowflake for Tracking Identifier Crosswalk data...")
print(f"Date Range: {startdate} to {enddate}")

loader = DataLoader()

crosswalk_df = loader.load_from_snowflake(
    sql_file_path='../sql/loadNumbertoReferenceNumMatching.sql',
    params={'startdate': startdate}
)

print(f"\n✓ Loaded {len(crosswalk_df):,} rows from Snowflake")
print(f"  Columns: {len(crosswalk_df.columns)}")
crosswalk_df.head()

Querying Snowflake for Tracking Identifier Crosswalk data...
Date Range: 2026-04-01 to 2026-05-06

/home/azureuser/trackingContextBuilder/trackingContextBuilder/scripts/data_preparation/load.py:160: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.snowflake_conn)

✓ Loaded 3,082,351 rows from Snowflake
  Columns: 4

   LOADNUMBER PARTYCODE           REFNUM CARRIER_CODE
0   551822026  C8636552  YHTNEY99NP8YHZZ     T5251301
1   549377667     C7419             RBTW     T6132390
2   549821170  C6944171        204520842        T5363
3   549549294  C8005159         11379219     T3861570
4   552141683  C8837520     ORD000525318      T401780

## 3. Extract Load Identifiers from Email Subjects

Create functions to:
1. Extract potential load identifiers from email subject lines (patterns like "Load #: 123456", "REF #: 123456", etc.)
2. Match extracted identifiers against the crosswalk data to find associated party codes

In [52]:
import re
from typing import List

def extract_load_identifiers(subject: str) -> List[str]:
    """
    Extract potential load identifiers from an email subject line.
    
    Patterns detected:
    - 8-12 digit numbers (common load number format)
    - Letter-digit combinations (e.g., CHR123456, ABC-123456)
    - "Load #: 123456" or "Load#: 123456"
    - "REF #: 123456" or "REF#: 123456"
    - "Load 123456" or "Load# 123456"
    - "Reference: 123456" or "Ref: 123456"
    - "Order: 123456" or "ORD# 123456"
    - "Shipment: 123456" or "SHIP# 123456"
    - Standalone numbers that could be load numbers (6+ digits)
    - Alphanumeric identifiers like "CHR123456", "L-123456", etc.
    
    Args:
        subject: Email subject line
        
    Returns:
        List of unique potential load identifiers (as strings)
    """
    if pd.isna(subject) or not isinstance(subject, str):
        return []
    
    subject_upper = str(subject).upper()
    identifiers = set()
    
    # Pattern 1: 8-12 digit numbers (common load number format)
    pattern1 = re.findall(r'\b\d{8,12}\b', subject_upper)
    identifiers.update(pattern1)
    
    # Pattern 2: Letter-digit combinations (e.g., CHR123456, ABC-123456)
    pattern2 = re.findall(r'\b[A-Z]{2,4}-?\d{6,10}\b', subject_upper)
    identifiers.update(pattern2)
    
    # Pattern 3: Reference patterns (REF: 123456, REF# 123456, Reference: 123456)
    pattern3 = re.findall(r'(?:REF(?:ERENCE)?)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern3)
    
    # Pattern 4: Load patterns (LOAD: 123456, LID: 123456, Load# 123456)
    pattern4 = re.findall(r'(?:LOAD|LID)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern4)
    
    # Pattern 5: Order patterns (ORDER: 123456, ORD# 123456)
    pattern5 = re.findall(r'(?:ORDER|ORD)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern5)
    
    # Pattern 6: Shipment patterns (SHIPMENT: 123456, SHIP# 123456)
    pattern6 = re.findall(r'(?:SHIPMENT|SHIP)[:\s#]*([A-Z0-9]{6,12})', subject_upper)
    identifiers.update(pattern6)
    
    # Pattern 7: Common prefixes followed by numbers/alphanumeric
    # Matches: "CHR123456", "L-123456", "LOAD-123"
    pattern7 = re.findall(r'\b(?:CHR|L)[:\-\s]?([A-Z0-9]+)\b', subject_upper)
    identifiers.update(pattern7)
    
    # Pattern 8: Standalone numbers that could be load numbers (6-7 digits)
    # This catches shorter numbers that might be load IDs without keywords
    pattern8 = re.findall(r'\b(\d{6,7})\b', subject_upper)
    identifiers.update(pattern8)
    
    # Pattern 9: Hash/pound sign followed by number
    # Matches: "#123456", "# 123456"
    pattern9 = re.findall(r'#\s*(\d{6,12})\b', subject_upper)
    identifiers.update(pattern9)
    
    # Clean up and return unique identifiers
    # Remove any empty strings and ensure all are uppercase
    cleaned_identifiers = [id.strip().upper() for id in identifiers if id.strip()]
    
    return list(set(cleaned_identifiers))  # Return unique values only


print("✓ Load identifier extraction function created")
print("  - extract_load_identifiers(): Extract IDs from subject line")

✓ Load identifier extraction function created
  - extract_load_identifiers(): Extract IDs from subject line

In [53]:
# Batch processing function to enrich dataframe with crosswalk data
def enrich_emails_with_crosswalk(email_df, crosswalk_df, chunk_size=100000):
    """
    Process emails in chunks and add loadnumber, partycode, and carrier_code columns from crosswalk matches.
    
    Args:
        email_df: DataFrame with email data including SUBJECT column
        crosswalk_df: DataFrame with REFNUM, LOADNUMBER, PARTYCODE, CARRIER_CODE columns
        chunk_size: Number of rows to process per chunk
        
    Returns:
        DataFrame with added columns: extracted_identifiers, matched_refnums, loadnumbers, partycodes, carrier_code, match_count
    """
    import gc
    
    total_rows = len(email_df)
    num_chunks = (total_rows + chunk_size - 1) // chunk_size
    
    print(f"\n{'='*80}")
    print(f"Enriching Email DataFrame with Crosswalk Data (Batch Processing)")
    print(f"{'='*80}")
    print(f"Total emails: {total_rows:,}")
    print(f"Chunk size: {chunk_size:,}")
    print(f"Number of chunks: {num_chunks}")
    print(f"Crosswalk records: {len(crosswalk_df):,}")
    print(f"{'='*80}\n")
    
    # Build crosswalk lookup once for efficiency
    print("Building crosswalk lookup dictionary...")
    crosswalk_lookup = {}
    for _, row in crosswalk_df.iterrows():
        refnum = str(row['REFNUM']).upper()
        if pd.notna(refnum):
            crosswalk_lookup[refnum] = {
                'loadnumber': str(row['LOADNUMBER']),
                'partycode': row['PARTYCODE'],
                'carrier_code': row.get('CARRIER_CODE', None)  # Get carrier_code, default to None if not present
            }
    print(f"✓ Crosswalk lookup built with {len(crosswalk_lookup):,} unique REFNUMs\n")
    
    # Initialize result lists
    all_extracted_ids = []
    all_matched_refnums = []
    all_loadnumbers = []
    all_partycodes = []
    all_carrier_codes = []
    all_match_counts = []
    
    # Process in chunks
    for chunk_num in range(num_chunks):
        start_idx = chunk_num * chunk_size
        end_idx = min((chunk_num + 1) * chunk_size, total_rows)
        
        print(f"📧 Processing chunk {chunk_num + 1}/{num_chunks}: rows {start_idx:,} to {end_idx:,}...")
        
        # Get chunk
        chunk = email_df.iloc[start_idx:end_idx]
        
        # Process each email in chunk
        chunk_extracted = []
        chunk_matched = []
        chunk_loadnums = []
        chunk_partycodes = []
        chunk_carrier_codes = []
        chunk_counts = []
        
        for _, row in chunk.iterrows():
            # Extract identifiers
            extracted_ids = extract_load_identifiers(row['SUBJECT'])
            
            # Match against crosswalk
            matched_refnums = []
            loadnumbers = set()
            partycodes = set()
            carrier_code = None  # Single value, not a set
            
            for identifier in extracted_ids:
                identifier_upper = identifier.upper()
                if identifier_upper in crosswalk_lookup:
                    matched_refnums.append(identifier_upper)
                    loadnumbers.add(crosswalk_lookup[identifier_upper]['loadnumber'])
                    partycodes.add(crosswalk_lookup[identifier_upper]['partycode'])
                    # Get the first carrier_code found (since there's only one per email)
                    if carrier_code is None:
                        carrier_code = crosswalk_lookup[identifier_upper]['carrier_code']
            
            # Store results
            chunk_extracted.append(extracted_ids)
            chunk_matched.append(matched_refnums)
            chunk_loadnums.append(list(loadnumbers))
            chunk_partycodes.append(list(partycodes))
            chunk_carrier_codes.append(carrier_code)  # Store as single value
            chunk_counts.append(len(matched_refnums))
        
        # Add chunk results to all results
        all_extracted_ids.extend(chunk_extracted)
        all_matched_refnums.extend(chunk_matched)
        all_loadnumbers.extend(chunk_loadnums)
        all_partycodes.extend(chunk_partycodes)
        all_carrier_codes.extend(chunk_carrier_codes)
        all_match_counts.extend(chunk_counts)
        
        # Clean up
        del chunk
        gc.collect()
    
    # Add columns to original dataframe
    print(f"\n✓ All chunks processed. Adding columns to dataframe...")
    email_df['extracted_identifiers'] = all_extracted_ids
    email_df['matched_refnums'] = all_matched_refnums
    email_df['loadnumbers'] = all_loadnumbers
    email_df['partycodes'] = all_partycodes
    email_df['carrier_code'] = all_carrier_codes  # Single string value
    email_df['match_count'] = all_match_counts
    
    # Print summary statistics
    print(f"\n{'='*80}")
    print(f"📊 Enrichment Summary")
    print(f"{'='*80}")
    
    emails_with_extracted = sum(1 for x in all_extracted_ids if len(x) > 0)
    emails_with_matches = sum(1 for x in all_match_counts if x > 0)
    total_loadnums = sum(len(x) for x in all_loadnumbers)
    total_partycodes = sum(len(x) for x in all_partycodes)
    emails_with_carrier_code = sum(1 for x in all_carrier_codes if pd.notna(x))
    
    print(f"Emails with extracted identifiers: {emails_with_extracted:,} ({emails_with_extracted/total_rows*100:.1f}%)")
    print(f"Emails with crosswalk matches: {emails_with_matches:,} ({emails_with_matches/total_rows*100:.1f}%)")
    print(f"Total load numbers found: {total_loadnums:,}")
    print(f"Total party codes found: {total_partycodes:,}")
    print(f"Emails with carrier code: {emails_with_carrier_code:,} ({emails_with_carrier_code/total_rows*100:.1f}%)")
    print(f"Average identifiers per email: {sum(len(x) for x in all_extracted_ids)/total_rows:.2f}")
    print(f"Average matches per email: {sum(all_match_counts)/total_rows:.2f}")
    print(f"{'='*80}\n")
    
    return email_df

print("✅ Batch enrichment function created: enrich_emails_with_crosswalk()")

✅ Batch enrichment function created: enrich_emails_with_crosswalk()

### Enrich Email DataFrame with Crosswalk Data (Batch Processing)

In [54]:
# Enrich the email dataframe with crosswalk data using batch processing
# This will add the following columns:
# - extracted_identifiers: All IDs found in subject
# - matched_refnums: IDs that matched in crosswalk
# - loadnumbers: Load numbers from crosswalk
# - partycodes: Party codes from crosswalk
# - match_count: Number of matches found

df_enriched = enrich_emails_with_crosswalk(
    email_df=df,
    crosswalk_df=crosswalk_df,
    chunk_size=100000  # Adjust based on your memory constraints
)

print("✅ Dataframe enriched with crosswalk data!")
print(f"\nNew columns added: {['extracted_identifiers', 'matched_refnums', 'loadnumbers', 'partycodes', 'match_count']}")
print(f"\nDataframe shape: {df_enriched.shape}")
print(f"\nSample of enriched data:")
df_enriched[['SUBJECT', 'extracted_identifiers', 'matched_refnums', 'loadnumbers', 'partycodes', 'match_count']].head(10)

================================================================================
Enriching Email DataFrame with Crosswalk Data (Batch Processing)
================================================================================
Total emails: 237,890
Chunk size: 100,000
Number of chunks: 3
Crosswalk records: 3,082,351
================================================================================

Building crosswalk lookup dictionary...
✓ Crosswalk lookup built with 2,199,983 unique REFNUMs

📧 Processing chunk 1/3: rows 0 to 100,000...
✓ Crosswalk lookup built with 2,199,983 unique REFNUMs

📧 Processing chunk 1/3: rows 0 to 100,000...
📧 Processing chunk 2/3: rows 100,000 to 200,000...
📧 Processing chunk 2/3: rows 100,000 to 200,000...
📧 Processing chunk 3/3: rows 200,000 to 237,890...
📧 Processing chunk 3/3: rows 200,000 to 237,890...

✓ All chunks processed. Adding columns to dataframe...

================================================================================
📊 Enrichment Summary
================================================================================

✓ All chunks processed. Adding columns to dataframe...

================================================================================
📊 Enrichment Summary
================================================================================
Emails with extracted identifiers: 165,034 (69.4%)
Emails with crosswalk matches: 75,409 (31.7%)
Total load numbers found: 79,750
Total party codes found: 77,786
Emails with carrier code: 75,409 (31.7%)
Average identifiers per email: 1.24
Average matches per email: 0.34
================================================================================

Emails with extracted identifiers: 165,034 (69.4%)
Emails with crosswalk matches: 75,409 (31.7%)
Total load numbers found: 79,750
Total party codes found: 77,786
Emails with carrier code: 75,409 (31.7%)
Average identifiers per email: 1.24
Average matches per email: 0.34
================================================================================

✅ Dataframe enriched with crosswalk data!

New columns added: ['extracted_identifiers', 'matched_refnums', 'loadnumbers', 'partycodes', 'match_count']

Dataframe shape: (237890, 25)

Sample of enriched data:
✅ Dataframe enriched with crosswalk data!

New columns added: ['extracted_identifiers', 'matched_refnums', 'loadnumbers', 'partycodes', 'match_count']

Dataframe shape: (237890, 25)

Sample of enriched data:

,SUBJECT,extracted_identifiers,matched_refnums,loadnumbers,partycodes,match_count
0,FORVIA MTY_FAUM0416OT2 MX 549993775 // XB 5499...,"[549993932, 549994444, 549993775]","[549993932, 549994444, 549993775]","[549993932, 549994444, 549993775]",[C8590128],3
1,Re: FW: Need ETA,[],[],[],[],0
2,RE: Burgess load ETA,[OAD],[],[],[],0
3,Re: Need Driver Information for 550503524,[550503524],[550503524],[550503524],[C7437456],1
4,RE: Inform Pull ECD15010023 order# 8142887801...,"[ECD15010023, 8142887804, 8142887801]",[],[],[],0
5,RE: HSD to YF Dicex - Wk 4/6,[],[],[],[],0
6,RE: EMBARQUE SULZER 14 ABRIL 2026,[],[],[],[],0
7,"RE: Urgent Delivery - 8006679284, 8006679285 &...","[8006679285, 8006679268, 8006679284]","[8006679285, 8006679268]",[549114643],[C8603025],2
8,Re: PACKING 75482-III -CHR Order # 1732248443 ...,"[1732248443, ORDER]",[ORDER],[550286968],[C1788806],1
9,RE: License plate entered - Shipment # 5482854...,"[AREDO, ICENSE, 548285421]",[],[],[],0

### Analyze Enriched Results

In [55]:
# Example 1: Filter emails that have matches
emails_with_matches = df_enriched[df_enriched['match_count'] > 0]
print(f"📊 Emails with crosswalk matches: {len(emails_with_matches):,}")
print(f"\nSample matched emails:")
print(emails_with_matches[['SUBJECT', 'matched_refnums', 'loadnumbers', 'partycodes']].head())

print("\n" + "="*80 + "\n")

# Example 2: Filter emails for a specific partycode
if len(emails_with_matches) > 0 and len(emails_with_matches.iloc[0]['partycodes']) > 0:
    example_partycode = emails_with_matches.iloc[0]['partycodes'][0]
    emails_for_party = df_enriched[df_enriched['partycodes'].apply(lambda x: example_partycode in x)]
    print(f"📧 Emails for partycode {example_partycode}: {len(emails_for_party):,}")
    
print("\n" + "="*80 + "\n")

# Example 3: Filter emails for a specific load number
if len(emails_with_matches) > 0 and len(emails_with_matches.iloc[0]['loadnumbers']) > 0:
    example_loadnum = emails_with_matches.iloc[0]['loadnumbers'][0]
    emails_for_load = df_enriched[df_enriched['loadnumbers'].apply(lambda x: example_loadnum in x)]
    print(f"📦 Emails for load number {example_loadnum}: {len(emails_for_load):,}")
    print(emails_for_load[['SUBJECT', 'SENT_DATE', 'TIME_SENT_UTC']].head())

print("\n" + "="*80 + "\n")

# Example 4: Emails that didn't match
no_match = df_enriched[df_enriched['match_count'] == 0]
print(f"⚠️  Emails without matches: {len(no_match):,}")
if len(no_match) > 0:
    print("\nSample subjects without matches:")
    for i, subject in enumerate(no_match['SUBJECT'].head(5)):
        print(f"  {i+1}. {subject}")

📊 Emails with crosswalk matches: 75,409

Sample matched emails:
                                              SUBJECT  \
0   FORVIA MTY_FAUM0416OT2 MX 549993775 // XB 5499...
3           Re: Need Driver Information for 550503524
7   RE: Urgent Delivery - 8006679284, 8006679285 &...
8   Re: PACKING 75482-III -CHR Order # 1732248443 ...
17  Re: Navisphere Carrier Load Confirmation - Loa...

                      matched_refnums                        loadnumbers  \
0   [549993932, 549994444, 549993775]  [549993932, 549994444, 549993775]
3                         [550503524]                        [550503524]
7            [8006679285, 8006679268]                        [549114643]
8                             [ORDER]                        [550286968]
17                        [551793772]                        [551793772]

    partycodes
0   [C8590128]
3   [C7437456]
7   [C8603025]
8   [C1788806]
17  [C8831063]

================================================================================

📧 Emails for partycode C8590128: 57

================================================================================

📦 Emails for load number 549993932: 2
                                                  SUBJECT   SENT_DATE  \
0       FORVIA MTY_FAUM0416OT2 MX 549993775 // XB 5499...  2026-04-15
154288  RE: FORVIA MTY_FAUM0416OT2 MX 549993775 // XB ...  2026-04-16

                    TIME_SENT_UTC
0      2026-04-15 19:40:42.968064
154288 2026-04-16 08:32:57.176177

================================================================================

📧 Emails for partycode C8590128: 57

================================================================================

📦 Emails for load number 549993932: 2
                                                  SUBJECT   SENT_DATE  \
0       FORVIA MTY_FAUM0416OT2 MX 549993775 // XB 5499...  2026-04-15
154288  RE: FORVIA MTY_FAUM0416OT2 MX 549993775 // XB ...  2026-04-16

                    TIME_SENT_UTC
0      2026-04-15 19:40:42.968064
154288 2026-04-16 08:32:57.176177

================================================================================

⚠️  Emails without matches: 162,481

Sample subjects without matches:
  1. Re: FW: Need ETA
  2. RE: Burgess load ETA
  3. RE: Inform Pull  ECD15010023 order# 8142887801, 8142887804 ,  (IGS USA )  - HUB AMS / ** RDD is : ASAP **
  4. RE: HSD to YF Dicex - Wk 4/6
  5. RE: EMBARQUE SULZER 14 ABRIL 2026
⚠️  Emails without matches: 162,481

Sample subjects without matches:
  1. Re: FW: Need ETA
  2. RE: Burgess load ETA
  3. RE: Inform Pull  ECD15010023 order# 8142887801, 8142887804 ,  (IGS USA )  - HUB AMS / ** RDD is : ASAP **
  4. RE: HSD to YF Dicex - Wk 4/6
  5. RE: EMBARQUE SULZER 14 ABRIL 2026

In [56]:
df_enriched.columns

Index(['CONVERSATION_ID', 'MESSAGE_ID', 'SUBJECT', 'EMAIL_TEXT', 'SENDER',
       'SENDER_DOMAIN', 'SENDER_IS_CHR', 'RECIPIENT', 'RECIPIENT_DOMAIN',
       'RECIPIENT_IS_CHR', 'TIME_SENT_UTC', 'SENT_DATE', 'SENT_HOUR',
       'TIME_RECEIVED_UTC', 'MAILBOXES', 'CLASSIFICATION', 'CATEGORIES',
       'MONTHSTARTDATE', 'WORKDAYS', 'extracted_identifiers',
       'matched_refnums', 'loadnumbers', 'partycodes', 'carrier_code',
       'match_count'],
      dtype='object')

In [57]:
matches_crosswalk = df_enriched[
    (df_enriched['partycodes'].notnull()) & 
    (df_enriched['partycodes'].apply(lambda x: len(x) > 0))
][['CONVERSATION_ID','loadnumbers','partycodes']]
# matches_crosswalk

In [58]:
df_final = pd.merge(df_enriched, matches_crosswalk.add_suffix('_final'), how='left', left_on='CONVERSATION_ID', right_on='CONVERSATION_ID_final')
df_final.shape

(443319, 28)

In [59]:
df_final.groupby('MESSAGE_ID').agg({'CONVERSATION_ID':'count'}).reset_index()

                                  MESSAGE_ID  CONVERSATION_ID
0       000089de-e949-4a6f-951a-985b7d67f198                1
1       000099ee-7189-4a94-aeec-06d603a56210                2
2       0000c12d-e439-4c9d-94f3-6cdf70c8ac69                1
3       0000e27d-6c45-43dd-a7ff-c7965797e694                1
4       00011b2a-4311-43c4-b1cf-5a9291cb7482                1
...                                      ...              ...
237885  ffff0603-6ce0-4271-889a-b4316bc89826                1
237886  ffff550d-67c4-411c-b891-8f3226fb1716                2
237887  ffff8f84-6be3-4d60-a07a-6a16cbd32e8e                4
237888  ffffad87-b85f-4a71-8248-53a224c8c435                1
237889  ffffca4d-50e9-4d81-8f54-cf4d5d048169                1

[237890 rows x 2 columns]

In [60]:
df_final[df_final['MESSAGE_ID']=='000099ee-7189-4a94-aeec-06d603a56210'].drop(columns=['EMAIL_TEXT']) #.to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/tester.csv', index=False)

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,TIME_SENT_UTC,...,WORKDAYS,extracted_identifiers,matched_refnums,loadnumbers,partycodes,carrier_code,match_count,CONVERSATION_ID_final,loadnumbers_final,partycodes_final
407089,AAQkADcxNjMxYTgyLTc3NTYtNDdiYS1hMjYwLTJjZTAwYj...,000099ee-7189-4a94-aeec-06d603a56210,RE: 3174113,biolab@kikcorp.com,kikcorp.com,0,"[ ""KIK-Pool@chrobinson.com"", ""biolab@kikcorp...","[ ""chrobinson.com"", ""kikcorp.com""]","[ 0, 1]",2026-04-14 21:16:10.452860,...,22,[3174113],[3174113],[549883632],[C665729],T3088892,1,AAQkADcxNjMxYTgyLTc3NTYtNDdiYS1hMjYwLTJjZTAwYj...,[549883632],[C665729]
407090,AAQkADcxNjMxYTgyLTc3NTYtNDdiYS1hMjYwLTJjZTAwYj...,000099ee-7189-4a94-aeec-06d603a56210,RE: 3174113,biolab@kikcorp.com,kikcorp.com,0,"[ ""KIK-Pool@chrobinson.com"", ""biolab@kikcorp...","[ ""chrobinson.com"", ""kikcorp.com""]","[ 0, 1]",2026-04-14 21:16:10.452860,...,22,[3174113],[3174113],[549883632],[C665729],T3088892,1,AAQkADcxNjMxYTgyLTc3NTYtNDdiYS1hMjYwLTJjZTAwYj...,[549883632],[C665729]

In [61]:
df_final = df_final.drop_duplicates(subset=['MESSAGE_ID'], keep='first')
df_final.shape

(237890, 28)

### Final Match Summary

In [62]:
# Summary statistics for final matches
total_emails = len(df_final)

# Original match rate (before join with matches_crosswalk)
emails_with_original_match = df_enriched[
    (df_enriched['partycodes'].notnull()) & 
    (df_enriched['partycodes'].apply(lambda x: len(x) > 0))
]
num_original_matches = len(emails_with_original_match)
original_match_percentage = (num_original_matches / total_emails * 100) if total_emails > 0 else 0

# Final match rate (after join with matches_crosswalk)
emails_with_final_match = df_final[
    (df_final['partycodes_final'].notnull()) & 
    (df_final['partycodes_final'].apply(lambda x: len(x) > 0 if isinstance(x, list) else False))
]
num_emails_with_match = len(emails_with_final_match)
match_percentage = (num_emails_with_match / total_emails * 100) if total_emails > 0 else 0

print("="*80)
print("📊 FINAL MATCH SUMMARY")
print("="*80)
print(f"\nTotal emails in dataset: {total_emails:,}")

print(f"\n{'ORIGINAL MATCHES (df_enriched):':-^80}")
print(f"Emails with party code matches: {num_original_matches:,}")
print(f"Original match rate: {original_match_percentage:.2f}%")

print(f"\n{'FINAL MATCHES (df_final after join):':-^80}")
print(f"Emails with party code matches: {num_emails_with_match:,}")
print(f"Final match rate: {match_percentage:.2f}%")

print(f"\n{'COMPARISON:':-^80}")
if num_emails_with_match == num_original_matches:
    print(f"✓ Match rates are the same - no change from join")
else:
    diff = num_emails_with_match - num_original_matches
    diff_pct = match_percentage - original_match_percentage
    print(f"Change: {diff:+,} emails ({diff_pct:+.2f} percentage points)")

print(f"\nEmails without matches: {total_emails - num_emails_with_match:,} ({100 - match_percentage:.2f}%)")

# Count unique party codes and load numbers in final matches
if num_emails_with_match > 0:
    all_final_partycodes = set()
    all_final_loadnums = set()
    
    for _, row in emails_with_final_match.iterrows():
        if isinstance(row['partycodes_final'], list):
            all_final_partycodes.update(row['partycodes_final'])
        if isinstance(row['loadnumbers_final'], list):
            all_final_loadnums.update(row['loadnumbers_final'])
    
    print(f"\nUnique party codes identified: {len(all_final_partycodes):,}")
    print(f"Unique load numbers identified: {len(all_final_loadnums):,}")

print("="*80)

================================================================================
📊 FINAL MATCH SUMMARY
================================================================================

Total emails in dataset: 237,890

------------------------ORIGINAL MATCHES (df_enriched):-------------------------
Emails with party code matches: 75,409
Original match rate: 31.70%

----------------------FINAL MATCHES (df_final after join):----------------------
Emails with party code matches: 75,531
Final match rate: 31.75%

----------------------------------COMPARISON:-----------------------------------
Change: +122 emails (+0.05 percentage points)

Emails without matches: 162,359 (68.25%)

Unique party codes identified: 3,939
Unique load numbers identified: 20,745
================================================================================

Unique party codes identified: 3,939
Unique load numbers identified: 20,745
================================================================================

In [43]:
df_final.columns

Index(['CONVERSATION_ID', 'MESSAGE_ID', 'SUBJECT', 'EMAIL_TEXT', 'SENDER',
       'SENDER_DOMAIN', 'SENDER_IS_CHR', 'RECIPIENT', 'RECIPIENT_DOMAIN',
       'RECIPIENT_IS_CHR', 'TIME_SENT_UTC', 'SENT_DATE', 'SENT_HOUR',
       'TIME_RECEIVED_UTC', 'MAILBOXES', 'CLASSIFICATION', 'CATEGORIES',
       'MONTHSTARTDATE', 'WORKDAYS', 'extracted_identifiers',
       'matched_refnums', 'loadnumbers', 'partycodes', 'carrier_codes',
       'match_count', 'CONVERSATION_ID_final', 'loadnumbers_final',
       'partycodes_final'],
      dtype='object')

## 4. Filter Out Internal CHR Emails

Remove emails where CHR is sending only to other CHR recipients (internal emails).
Keep emails where:
- SENDER_IS_CHR = 1 AND at least one recipient is external (RECIPIENT_IS_CHR contains 0)
- OR SENDER_IS_CHR = 0 (external sender)

In [63]:
def filter_external_emails(df):
    """
    Filter out internal CHR emails (CHR sender to only CHR recipients).
    
    Keeps emails where:
    - SENDER_IS_CHR = 1 AND RECIPIENT_IS_CHR contains at least one 0 (external recipient)
    - OR SENDER_IS_CHR = 0 (external sender - keep all regardless of recipients)
    
    Removes emails where:
    - SENDER_IS_CHR = 1 AND RECIPIENT_IS_CHR = [1] (only internal CHR recipients)
    
    Args:
        df: DataFrame with SENDER_IS_CHR and RECIPIENT_IS_CHR columns
        
    Returns:
        Filtered DataFrame with internal CHR emails removed
    """
    original_count = len(df)
    
    # Create a mask for rows to keep
    # Keep if: sender is external (SENDER_IS_CHR = 0) OR (sender is CHR AND has external recipients)
    def has_external_recipient(recipient_array):
        """Check if the RECIPIENT_IS_CHR array contains at least one 0."""
        if pd.isna(recipient_array):
            return False
        if isinstance(recipient_array, list):
            return 0 in recipient_array
        return False
    
    # Mask: Keep all emails where sender is NOT CHR (0), 
    # OR where sender IS CHR (1) but has at least one external recipient (0 in array)
    mask = (
        (df['SENDER_IS_CHR'] == 0) |  # External sender - keep all
        (
            (df['SENDER_IS_CHR'] == 1) &  # CHR sender
            df['RECIPIENT_IS_CHR'].apply(has_external_recipient)  # Has external recipient
        )
    )
    
    df_filtered = df[mask].copy()
    
    removed_count = original_count - len(df_filtered)
    
    print("="*80)
    print("📧 INTERNAL EMAIL FILTERING")
    print("="*80)
    print(f"Original email count: {original_count:,}")
    print(f"Emails removed (CHR → only CHR recipients): {removed_count:,}")
    print(f"Emails remaining: {len(df_filtered):,}")
    print(f"Retention rate: {len(df_filtered)/original_count*100:.2f}%")
    print("="*80)
    
    return df_filtered

print("✅ Filter function created: filter_external_emails()")

✅ Filter function created: filter_external_emails()

In [64]:
# Apply the filter to remove internal CHR emails
df_final_filtered = filter_external_emails(df_final)

print(f"\n✅ Filtered dataframe created: df_final_filtered")
print(f"Shape: {df_final_filtered.shape}")
df_final_filtered.head()

================================================================================
📧 INTERNAL EMAIL FILTERING
================================================================================
Original email count: 237,890
Emails removed (CHR → only CHR recipients): 61,920
Emails remaining: 175,970
Retention rate: 73.97%
================================================================================

✅ Filtered dataframe created: df_final_filtered
Shape: (175970, 28)

,CONVERSATION_ID,MESSAGE_ID,SUBJECT,EMAIL_TEXT,SENDER,SENDER_DOMAIN,SENDER_IS_CHR,RECIPIENT,RECIPIENT_DOMAIN,RECIPIENT_IS_CHR,...,WORKDAYS,extracted_identifiers,matched_refnums,loadnumbers,partycodes,carrier_code,match_count,CONVERSATION_ID_final,loadnumbers_final,partycodes_final
2,AAQkADZmNDg3YzJlLTUwODgtNDAwNi1iNGM5LTU3ZmZiY2...,94c882ee-357f-40eb-8d32-caab7cf1caad,Re: FW: Need ETA,"<html><head>\r<meta http-equiv=""Content-Type"" ...",nhaley@arrivelogistics.com,arrivelogistics.com,0,"[ ""BenjaminMooreTeam@chrobinson.com""]","[ ""chrobinson.com""]",[ 1],...,22,[],[],[],[],None,0,NaN,NaN,NaN
3,AAQkADQzOTE2ZmNmLTMxNTQtNDNhOC1hMzkzLWUyNjMzOG...,f61e7c86-ffc6-4e5f-bde5-2f4f70cd43bb,RE: Burgess load ETA,"<html><head>\r<meta http-equiv=""Content-Type"" ...",tedpawlak@dar-techinc.com,dar-techinc.com,0,"[ ""kschneider@dar-techinc.com"", ""Chris.Pavla...","[ ""chrobinson.com"", ""dar-techinc.com""]","[ 1, 0]",...,22,[OAD],[],[],[],None,0,NaN,NaN,NaN
4,AAQkAGVlMTYxMTk0LTM1ZTktNGEwNy05MTMzLWM5MWRlMz...,a3eecc4f-5ff3-496e-9d53-35760704ebfc,Re: Need Driver Information for 550503524,"<html><head>\r<meta http-equiv=""Content-Type"" ...",dispatch.support@munisatrans.com,munisatrans.com,0,"[ ""Giovanni.Tregembo@chrobinson.com"", ""dispa...","[ ""munisatrans.com"", ""chrobinson.com""]","[ 0, 1]",...,22,[550503524],[550503524],[550503524],[C7437456],T5184924,1,AAQkAGVlMTYxMTk0LTM1ZTktNGEwNy05MTMzLWM5MWRlMz...,[550503524],[C7437456]
9,AAQkAGU2NDNmYjVlLWQxZjAtNGE5MS1hNzMzLTQ0Njc4ZD...,d2d34405-057c-4c5f-967f-a5fe67cded3f,RE: Inform Pull ECD15010023 order# 8142887801...,"<html><head>\r<meta http-equiv=""Content-Type"" ...",kaiyi.zhang@hou-ep.fii-na.com,hou-ep.fii-na.com,0,"[ ""hou2.logistics@hou-ep.fii-na.com"", ""Jonat...","[ ""chrobinson.com"", ""dsv.com"", ""deltaww.com...","[ 0, 1]",...,22,"[ECD15010023, 8142887804, 8142887801]",[],[],[],None,0,NaN,NaN,NaN
10,AAQkADUxYjQ3MDhlLTAxODctNDVhNy1iMjk2LTExZDY4OD...,aa5cbf65-585c-42a7-acbe-e83034135168,RE: HSD to YF Dicex - Wk 4/6,"<html><head>\r<meta http-equiv=""Content-Type"" ...",aerhardt@hollandspecial.com,hollandspecial.com,0,"[ ""Yanfeng@chrobinson.com"", ""sarai.ascanio@y...","[ ""hollandspecial.com"", ""chrobinson.com"", ""...","[ 0, 1]",...,22,[],[],[],[],None,0,NaN,NaN,NaN

## 5. Analyze Non-CHR Email Recipients by Carrier

Analyze which external email addresses each carrier communicates with and the distribution of emails sent to each recipient.

In [65]:
def analyze_carrier_recipients(df):
    """
    Analyze non-CHR email recipients by carrier code.
    
    For each carrier, this function:
    1. Extracts all recipient email addresses from the RECIPIENT field
    2. Filters to only non-CHR emails (not ending in @chrobinson.com)
    3. Calculates the percentage of emails sent to each non-CHR recipient
    
    Args:
        df: DataFrame with CARRIER_CODE and RECIPIENT columns
        
    Returns:
        DataFrame with columns:
        - carrier_code: The carrier code
        - non_chr_recipients: Array of non-CHR email addresses
        - recipient_percentages: Array of percentages (corresponding to non_chr_recipients)
    """
    import re
    from collections import Counter
    
    def extract_non_chr_emails(recipient_field):
        """Extract non-CHR email addresses from the RECIPIENT field."""
        if pd.isna(recipient_field) or recipient_field == '':
            return []
        
        # Extract all email addresses using regex
        email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
        emails = re.findall(email_pattern, str(recipient_field))
        
        # Filter to only non-CHR emails (not ending in @chrobinson.com)
        non_chr_emails = [
            email.lower() for email in emails 
            if not email.lower().endswith('@chrobinson.com')
        ]
        
        return non_chr_emails
    
    # Filter to only rows with carrier_code
    df_with_carrier = df[df['carrier_code'].notna()].copy()
    
    print("="*80)
    print("📊 ANALYZING NON-CHR RECIPIENTS BY CARRIER")
    print("="*80)
    print(f"Total emails with carrier code: {len(df_with_carrier):,}")
    print(f"Processing recipient email extraction...")
    print("="*80 + "\n")
    
    # Group by carrier_code and analyze recipients
    results = []
    
    for carrier_code, group in df_with_carrier.groupby('carrier_code'):
        # Count all non-CHR emails for this carrier
        all_non_chr_emails = []
        
        for _, row in group.iterrows():
            non_chr_emails = extract_non_chr_emails(row['RECIPIENT'])
            all_non_chr_emails.extend(non_chr_emails)
        
        if len(all_non_chr_emails) == 0:
            # No non-CHR recipients for this carrier
            continue
        
        # Count occurrences of each email
        email_counts = Counter(all_non_chr_emails)
        total_emails = len(all_non_chr_emails)
        
        # Sort by count (descending) to get most common recipients first
        sorted_emails = sorted(email_counts.items(), key=lambda x: x[1], reverse=True)
        
        # Extract emails and percentages in the same order
        non_chr_recipients = [email for email, count in sorted_emails]
        recipient_percentages = [
            round((count / total_emails) * 100, 2) 
            for email, count in sorted_emails
        ]
        
        results.append({
            'carrier_code': carrier_code,
            'non_chr_recipients': non_chr_recipients,
            'recipient_percentages': recipient_percentages,
            'total_non_chr_emails': total_emails,
            'unique_recipients': len(non_chr_recipients)
        })
    
    # Create result dataframe
    result_df = pd.DataFrame(results)
    
    # Sort by total_non_chr_emails descending
    result_df = result_df.sort_values('total_non_chr_emails', ascending=False).reset_index(drop=True)
    
    print("\n" + "="*80)
    print("📈 ANALYSIS SUMMARY")
    print("="*80)
    print(f"Carriers with non-CHR recipients: {len(result_df):,}")
    print(f"Total non-CHR email instances analyzed: {result_df['total_non_chr_emails'].sum():,}")
    print(f"\nTop 5 carriers by non-CHR email volume:")
    for i, row in result_df.head().iterrows():
        print(f"  {i+1}. {row['carrier_code']}: {row['total_non_chr_emails']:,} emails to {row['unique_recipients']} unique recipients")
    print("="*80)
    
    return result_df

print("✅ Carrier recipient analysis function created: analyze_carrier_recipients()")

✅ Carrier recipient analysis function created: analyze_carrier_recipients()

In [66]:
# Analyze non-CHR recipients by carrier
carrier_recipients_df = analyze_carrier_recipients(df_final_filtered)

print(f"\n✅ Analysis complete!")
print(f"\nResult dataframe columns:")
print(f"  - carrier_code: Carrier identifier")
print(f"  - non_chr_recipients: Array of non-CHR email addresses (sorted by frequency)")
print(f"  - recipient_percentages: Percentage of emails to each recipient (same order)")
print(f"  - total_non_chr_emails: Total number of non-CHR email instances")
print(f"  - unique_recipients: Count of unique non-CHR recipients")

carrier_recipients_df.head()

================================================================================
📊 ANALYZING NON-CHR RECIPIENTS BY CARRIER
================================================================================
Total emails with carrier code: 54,064
Processing recipient email extraction...
================================================================================


================================================================================
📈 ANALYSIS SUMMARY
================================================================================
Carriers with non-CHR recipients: 2,943
Total non-CHR email instances analyzed: 45,019

Top 5 carriers by non-CHR email volume:
  1. T5095432: 1,828 emails to 755 unique recipients
  2. T6035666: 1,487 emails to 46 unique recipients
  3. T5338852: 647 emails to 307 unique recipients
  4. T5112510: 488 emails to 219 unique recipients
  5. T6021175: 460 emails to 175 unique recipients
================================================================================

✅ Analysis complete!

Result dataframe columns:
  - carrier_code: Carrier identifier
  - non_chr_recipients: Array of non-CHR email addresses (sorted by frequency)
  - recipient_percentages: Percentage of emails to each recipient (same order)
  - total_non_chr_emails: Total number of non-CHR email instances
  - unique_recipients: Count of unique non-CHR recipients

================================================================================
📈 ANALYSIS SUMMARY
================================================================================
Carriers with non-CHR recipients: 2,943
Total non-CHR email instances analyzed: 45,019

Top 5 carriers by non-CHR email volume:
  1. T5095432: 1,828 emails to 755 unique recipients
  2. T6035666: 1,487 emails to 46 unique recipients
  3. T5338852: 647 emails to 307 unique recipients
  4. T5112510: 488 emails to 219 unique recipients
  5. T6021175: 460 emails to 175 unique recipients
================================================================================

✅ Analysis complete!

Result dataframe columns:
  - carrier_code: Carrier identifier
  - non_chr_recipients: Array of non-CHR email addresses (sorted by frequency)
  - recipient_percentages: Percentage of emails to each recipient (same order)
  - total_non_chr_emails: Total number of non-CHR email instances
  - unique_recipients: Count of unique non-CHR recipients

,carrier_code,non_chr_recipients,recipient_percentages,total_non_chr_emails,unique_recipients
0,T5095432,"[pickups@rjwgroup.com, customersupport@rjwgrou...","[1.59, 1.53, 1.04, 0.98, 0.82, 0.77, 0.71, 0.6...",1828,755
1,T6035666,"[dispatch@vannerinc.us, aurora@vannerinc.us, s...","[29.59, 6.86, 6.72, 6.32, 6.19, 5.04, 4.1, 4.1...",1487,46
2,T5338852,"[hector.hernandez@marelli.com, samantha.cabell...","[1.39, 1.39, 1.39, 1.24, 1.24, 1.08, 1.08, 1.0...",647,307
3,T5112510,"[import@chartaglobal.com, fiona.wang@hihlogist...","[2.05, 2.05, 1.64, 1.43, 1.43, 1.43, 1.43, 1.2...",488,219
4,T6021175,"[tracking@a2b-logistics.us, afterhours@a2b-log...","[5.22, 4.78, 3.7, 3.04, 2.83, 2.61, 2.61, 2.17...",460,175

### Example: View Top Recipients for a Specific Carrier

Let's examine the distribution of recipients for one carrier in detail.

In [67]:
# Example: View details for the carrier with the most non-CHR emails
if len(carrier_recipients_df) > 0:
    top_carrier = carrier_recipients_df.iloc[0]
    
    print("="*80)
    print(f"📧 CARRIER: {top_carrier['carrier_code']}")
    print("="*80)
    print(f"Total non-CHR emails: {top_carrier['total_non_chr_emails']:,}")
    print(f"Unique recipients: {top_carrier['unique_recipients']}")
    print(f"\nTop 10 Recipients (sorted by percentage):")
    print("-"*80)
    
    for i, (email, pct) in enumerate(zip(
        top_carrier['non_chr_recipients'][:10], 
        top_carrier['recipient_percentages'][:10]
    ), 1):
        print(f"{i:2d}. {email:50s} {pct:6.2f}%")
    
    print("="*80)
else:
    print("No carriers with non-CHR recipients found.")

================================================================================
📧 CARRIER: T5095432
================================================================================
Total non-CHR emails: 1,828
Unique recipients: 755

Top 10 Recipients (sorted by percentage):
--------------------------------------------------------------------------------
 1. pickups@rjwgroup.com                                 1.59%
 2. customersupport@rjwgroup.com                         1.53%
 3. wwtdom@aitworldwide.com                              1.04%
 4. emquantixlogistics@celanese.com                      0.98%
 5. celanesegrandpkwy@quantixscs.com                     0.82%
 6. ms.servicedelivery.rsd@arvato.com                    0.77%
 7. cperezojeda@aitworldwide.com                         0.71%
 8. jonathan.romo@mx.yazaki.com                          0.66%
 9. targetcustomerservice@saia.com                       0.66%
10. freightsolutions@norcal-ltl.com                      0.66%
================================================================================

### Identify Carriers with High Email Concentration

Sort carriers by the percentage of emails going to their top recipient to find carriers that send most emails to a single inbox.

In [68]:
# Sort carriers by the percentage going to their top recipient (first value in recipient_percentages)
# This shows carriers with high email concentration to a single inbox

carrier_recipients_sorted = carrier_recipients_df.copy()

# Extract the first percentage (top recipient percentage) for sorting
carrier_recipients_sorted['top_recipient_pct'] = carrier_recipients_sorted['recipient_percentages'].apply(
    lambda x: x[0] if isinstance(x, list) and len(x) > 0 else 0
)

# Sort by top recipient percentage descending
carrier_recipients_sorted = carrier_recipients_sorted.sort_values('top_recipient_pct', ascending=False).reset_index(drop=True)

print("="*80)
print("📊 CARRIERS SORTED BY EMAIL CONCENTRATION TO TOP RECIPIENT")
print("="*80)
print(f"Total carriers analyzed: {len(carrier_recipients_sorted):,}\n")
print("Top 20 carriers with highest concentration to single recipient:")
print("-"*80)
print(f"{'#':<4} {'Carrier':<15} {'Top %':<8} {'Top Recipient Email':<50}")
print("-"*80)

for i, row in carrier_recipients_sorted.head(20).iterrows():
    carrier = str(row['carrier_code'])[:14]  # Truncate if too long
    top_pct = row['top_recipient_pct']
    top_email = row['non_chr_recipients'][0] if len(row['non_chr_recipients']) > 0 else 'N/A'
    top_email_display = top_email[:49] if len(top_email) > 49 else top_email
    
    print(f"{i+1:<4} {carrier:<15} {top_pct:>6.2f}%  {top_email_display}")

print("="*80)

# Display the full dataframe sorted
carrier_recipients_sorted

================================================================================
📊 CARRIERS SORTED BY EMAIL CONCENTRATION TO TOP RECIPIENT
================================================================================
Total carriers analyzed: 2,943

Top 20 carriers with highest concentration to single recipient:
--------------------------------------------------------------------------------
#    Carrier         Top %    Top Recipient Email
--------------------------------------------------------------------------------
1    T6252252        100.00%  oscar.torres@anheuser-busch.com
2    T5191951        100.00%  robert.peter.ziegler@bd.com
3    T4856290        100.00%  customerops@drinkwaterloo.com
4    T4766461        100.00%  j.r.holder@whitecap.com
5    T3474           100.00%  angela.craig@pac.com
6    T3374088        100.00%  reworkmd@translogistix.com
7    T3283           100.00%  ardgeorgetown@ardtrucking.com
8    T3248239        100.00%  chuff@gojarrett.com
9    T3140847        100.00%  prabh@istlogistics.ca
10   T313694         100.00%  sebastienbrodeur@transportsn.com
11   T2120760        100.00%  shammi@sewa.ca
12   T3512533        100.00%  cpt-na-pkg-truck-ops_salt-midwest@cargill.com
13   T2999           100.00%  eatonlcc@uberfreight.com
14   T21407          100.00%  stephenwhite@piedmontcandy.com
15   T2668053        100.00%  bomalley@paketcorp.com
16   T257220         100.00%  dacton@4rampolymers.com
17   T2183342        100.00%  dispatch@daytodaylogistics.com
18   T248725         100.00%  marina.brown@danone.com
19   T2417321        100.00%  niagarabottling_osc@mailph.custhelp.com
20   T2091070        100.00%  sam@wenzellc.com
================================================================================

,carrier_code,non_chr_recipients,recipient_percentages,total_non_chr_emails,unique_recipients,top_recipient_pct
0,T6252252,[oscar.torres@anheuser-busch.com],[100.0],1,1,100.00
1,T5191951,[robert.peter.ziegler@bd.com],[100.0],2,1,100.00
2,T4856290,[customerops@drinkwaterloo.com],[100.0],2,1,100.00
3,T4766461,[j.r.holder@whitecap.com],[100.0],2,1,100.00
4,T3474,[angela.craig@pac.com],[100.0],2,1,100.00
...,...,...,...,...,...,...
2938,T5002636,"[polaris.nps@penske.com, polaris.npsplanning@p...","[2.44, 2.44, 2.44, 2.44, 2.44, 2.44, 2.44, 2.4...",123,60,2.44
2939,T5112510,"[import@chartaglobal.com, fiona.wang@hihlogist...","[2.05, 2.05, 1.64, 1.43, 1.43, 1.43, 1.43, 1.2...",488,219,2.05
2940,T5148626,"[sinuhe.rafael.argaez@aptiv.com, vpablos@rljon...","[1.59, 1.59, 1.59, 1.59, 1.59, 1.59, 1.59, 1.5...",252,77,1.59
2941,T5095432,"[pickups@rjwgroup.com, customersupport@rjwgrou...","[1.59, 1.53, 1.04, 0.98, 0.82, 0.77, 0.71, 0.6...",1828,755,1.59
2942,T5338852,"[hector.hernandez@marelli.com, samantha.cabell...","[1.39, 1.39, 1.39, 1.24, 1.24, 1.08, 1.08, 1.0...",647,307,1.39

In [69]:
carrier_recipients_sorted.to_csv('/home/azureuser/trackingContextBuilder/trackingContextBuilder/data/processed/carrier_recipient_analysis.csv', index=False)